### ISSUE TITLE
Stage#0 - Git Test [RU](S0) - Текст в вариантах ответа сливается (отступов не хватает)

### ISSUE THREAD

**Issue by ripetchor** [rolling-scopes-school/tasks#1065]
Слегка трудно понять, какая строчка к какому варианту ответа относится

![test](https://github.com/rolling-scopes-school/tasks/assets/115036520/40ffd723-ad11-4d65-9470-a2a38985d415)

**Comment by Ariorka** [comment]
Запрос на применение ваших изменений из вашего репозитория и/или указанной вами ветки, в процессе которого происходит ревью и обсуждение ваших изменений
