### ISSUE TITLE
[2023Q4]: Week-2 MODULE: Update "JavaScript. Evolution" Module: Translation, Additional Materials, and New Task Creation

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1102]
## Summary:
The "JavaScript. Evolution" module requires updates: translation to English, incorporation of additional materials, and the creation of a task similar to 'corejs-101'.

## Details:
The current "JavaScript. Evolution" module is slated for enhancements to increase its value to learners. The entire content of the module needs to be translated into English to cater to a broader audience. Furthermore, supplementary educational materials should be added to facilitate understanding and provide a more comprehensive learning experience. A new task, mirroring the complexity and format of 'corejs-101', should be introduced for practical application and reinforcement of learned concepts.

## Tasks:
1. Translate the complete content of the "JavaScript. Evolution" module to English.
2. Incorporate additional educational materials within the module.
3. Develop a new task similar to 'corejs-101' for this module.

## Expected Outcome:
Post-update, the "JavaScript. Evolution" module should be fully translated into English, supplemented with additional learning materials, and contain a new task comparable to 'corejs-101'.

## Additional Notes:
The translation should be accurate, and the new task should be well defined, offering meaningful practice. The additional materials need to be pertinent and effectively complement the existing content.

**Comment by v-yelina** [comment]
[#1190](https://github.com/rolling-scopes-school/tasks/pull/1190/)
