### ISSUE TITLE
 Cross-Check Library #2 - EkaterinaPanasiuk

### ISSUE THREAD

**Issue by EkaterinaPanasiuk** [rolling-scopes-school/tasks#1122]
https://ekaterinapanasiuk.github.io/rsSchool_Library1/library/     ------------Ссылка на деплой вашего проекта.
https://github.com/EkaterinaPanasiuk/rsSchool_Library1    -----------Ссылка на репозиторий с проектом на GitHub.
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/library/library-part2.md -------------Ссылка на задание.
![image](https://github.com/rolling-scopes-school/tasks/assets/105225301/cc694157-40c1-4b70-b5b6-49496651f0cb)
![image](https://github.com/rolling-scopes-school/tasks/assets/105225301/490bac13-7716-45b4-9832-464301beba85)

Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
Оценка в результате самопроверки с ее аргументацией:----------- 
Общая оценка 48 баллов:
блок <header> +2
 Welcome +2 
About +4. (не понятно как должна выглядеть высота стрелок с учетом сохранения расстояния межд картинкой и точками(40пх) (+2) + 5точек кнопку own(+2) 
 CoffeShop +4 
 Contacts +4 
 LibraryCard +4 
 <footer> + 2 
 не появляется горизонтальная полоса (+4) 
 элементы не выходят за пределы окна(+4) 
 элементы не наезжают друг на друга(+4) 
 адаптивное меню +12 
 отступ иконки юзера от правого края - 105px(+2)
  иконка юзера не прыгает(+2)
при нажатии на бургер-иконку плавно появляется адаптивное меню +4 
 фдаптивное меню скрывается резко(0)
ссылки в адаптивном меню работают(+2)
 PixelPerfect (+2)
---------------------------------------------------------------
25  --------Балл за cross-check из вашего Score.

**Comment by WiiJoy** [comment]
Привет, апелляции оформляются в другом [репозитории](https://github.com/rolling-scopes-school/support/issues/new?template=cross-check_appeal.md)

**Comment by EkaterinaPanasiuk** [comment]
СпасибО)
