### ISSUE TITLE
[2023Q4]: Week-5 Module: Update and Translate Module: "HTML Forms & Validation"

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1151]
## Summary:
The "HTML Forms & Validation" module needs translation into English and a comprehensive review of its existing materials to ensure they are up-to-date and relevant.

## Details:
The current module is in a language other than English, which limits its accessibility to a global audience. Additionally, it's crucial to review and possibly update the educational materials to make sure they are current and useful for the students.

## Tasks:
1. Translate the entire content of the ["HTML Forms & Validation" module](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-form) to English.
2. Review the current materials, including tutorials, examples, and exercises, for relevance and accuracy.

**Comment by haslie22** [comment]
PR [here](https://github.com/rolling-scopes-school/tasks/pull/1251)
