### ISSUE TITLE
[2023Q4]: week1 Translate Tasks CV

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1178]
## Summary:
The tasks for the "CV Project", both Part 1 "Markdown & Git" and Part 2 "HTML, CSS & Git Basics", need to be translated to make them accessible to a broader audience.

## Details:
The "CV Project" is an important part of our curriculum, and it is crucial that the tasks are available in English to accommodate non-native speakers and international students. The translation will make it easier for students to understand the requirements and objectives of the project.

## Tasks:
1. Translate the content of ["CV Project. Part 1 Markdown & Git"](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/git-markdown.md) to English.
2. Translate the content of ["CV Project. Part 2 HTML, CSS & Git Basics"](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/html-css-git.md) to English.
3. Review the translated tasks to ensure technical accuracy and clarity.
4. Update the project documentation to include the new translations.

## Expected Outcome:
Both parts of the "CV Project" should be fully translated into English, with accurate and clear descriptions of the project objectives and requirements.

**Comment by valerydluski** [comment]
https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(HTML%2BCSS%2BMarkdown).md
https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(markdown).md

**Comment by matthewTheWizzard** [comment]
https://github.com/rolling-scopes-school/tasks/pull/1181
