### ISSUE TITLE
[2023Q4]: Week-2 TASK: Creation of Short Tasks - "CoreJS: Numbers & Math Methods"

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1202]
## Summary:
To enhance our learning resources in JavaScript, focusing on numbers and each Math method, it is proposed to create short tasks similar to our CoreJS tasks. These tasks should provide hands-on experience and a deeper understanding of working with numbers and utilizing various Math methods in JavaScript.

## Details:
JavaScript numbers and Math methods are fundamental concepts that every developer should master. By introducing concise, targeted tasks, students can gain more practical experience and a solid understanding of these concepts. The tasks should be designed to be clear, focused, and cover each method comprehensively, allowing students to apply the learned concepts effectively in different contexts.

## Tasks:
1. **Identify Key Concepts:** List all the essential concepts related to JavaScript numbers and each Math method that should be covered by the tasks.
2. **Design Tasks:** Create concise and clear tasks that address each identified concept, ensuring they are engaging and provide adequate learning value.
3. **Create Instructions:** Write clear, concise instructions for each task, ensuring they are understandable and free from ambiguity.
4. **Develop Test Cases:** Formulate test cases for each task to validate the students' solutions effectively.
5. **Peer Review:** Have the tasks reviewed by peers to ensure clarity, relevance, and accuracy.
6. **Publish Tasks:** After review and any necessary revisions, publish the tasks for student access.

## Expected Outcome:
The creation of these new short tasks should facilitate a more enriched learning experience for students in understanding and applying JavaScript numbers and Math methods. These tasks should act as practical supplements to theoretical learning, aiding in the consolidation of fundamental concepts related to JavaScript numbers and Math methods.

**Comment by MikAleinik** [comment]
[PR #1](https://github.com/rolling-scopes-school/core-js-numbers/pull/1)

**Comment by MikAleinik** [comment]
[PR #2](https://github.com/rolling-scopes-school/core-js-numbers/pull/2)
