### ISSUE TITLE
[2023Q4]: Week-7 TASK: Creation of Short Tasks - "CoreJS: conditions and loops"

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1206]
## Summary:
We need to create a new set of tasks focusing on working with loops and conditions in JavaScript, to be incorporated into the 7th week of the curriculum. The aim is to solidify the students' understanding and application of loops and condition statements in JavaScript programming.

## Details:
The tasks will predominantly focus on the practical application of various loops and conditions in JavaScript. Existing tasks listed in the [core-js-101](https://github.com/mikhama/core-js-101/blob/master/src/07-conditions-n-loops-tasks.js) can serve as a basis for creating engaging and challenging tasks for the students. 

## Tasks:
1. **Review Existing Tasks:** Examine the tasks available in the provided core-js-101 link and determine their relevance and appropriateness for the intended learning outcomes.
2. **Develop New Tasks:** Create a series of new tasks that include a range of challenges from beginner to advanced, ensuring the coverage of all essential concepts related to conditions and loops.
3. **Provide Clear Instructions:** Each task should have concise and clear instructions, detailing the expected outcomes and any specific constraints or requirements.
4. **Create Test Cases:** Develop test cases for each task to allow students to validate their solutions effectively.
5. **Upload to GitHub:** Once finalized, upload the newly created tasks to the appropriate GitHub repository, ensuring accessibility to all students.

## Expected Outcome:
The introduction of the "conditions-n-loops-tasks" should enhance the learning experience by providing practical applications and challenges related to loops and conditions in JavaScript. The feedback received from the students will be crucial in refining the tasks for future iterations, ensuring continuous improvement and relevance.

**Comment by MikAleinik** [comment]
https://github.com/rolling-scopes-school/coreJs-conditions-n-loops-tasks
