### ISSUE TITLE
[2023Q4]: Week-7 Module: Creation of New Module - "Linters, Formatters, and Husky"

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1284]
## Summary:
To ensure our curriculum is up-to-date with best practices in development, we need to introduce a new module focusing on Linters, Formatters, and the usage of Husky for pre-commit hooks.

## Details:
In modern development, ensuring code quality, consistency, and avoiding potential pitfalls is crucial. Linters, formatters, and tools like Husky play a pivotal role in achieving these goals. This module should introduce these tools, their significance, and how to effectively integrate them into a development workflow.

## Tasks:
1. **Module Objectives**: Define clear learning outcomes for the module. Students should understand the importance of linting, code formatting, and how Husky can automate these before commits.
2. **Content Creation**: Develop comprehensive content covering:
   - Introduction to linting and formatters (e.g., ESLint, Prettier).
   - Setting up and configuring popular linters and formatters.
   - Common issues caught by linters and their significance.
   - Integrating linters with popular IDEs.
   - Introduction to Husky and its role in automating tasks before commits.
   - Setting up Husky for pre-commit linting and formatting.
3. **RS App Test Creation**: Create a test in RS App to evaluate students' understanding of linting, formatters, and Husky. This should include:
   - Multiple-choice questions on the theory and concepts. [ticket](https://github.com/rolling-scopes-school/tasks/issues/1285)
4. **Integration with Platform**: Ensure the module is accessible on our learning platform with all resources, links, and exercises properly structured.

## Expected Outcome:
A well-structured module on "Linters, Formatters, and Husky" that educates students on the importance of these tools and how to effectively integrate them into their development workflow, complemented by an evaluative test in the RS App.

**Comment by milothea** [comment]
#1300
