### ISSUE TITLE
[2023Q4] STAGE-1: Video and Text are not connected

### ISSUE THREAD

**Issue by maria-akulova** [rolling-scopes-school/tasks#1286]
Where:
1. Open the [page](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/basic-tools)
2. Look at the Theory part
3. The 2nd point is [Webinar: Browsers and VS Code – Installation and Setup (Ru)](https://www.youtube.com/watch?v=nd2VYxOsOwY)

Issue: 
The text link is about browsers and vs code in Russian.
But actually the video is about VS Code only and in English.

Solution:
If you want to have video in RU - you need the link to another source.
If the video is correct the link should be like this: "Visual Studio Code Tutorial for Beginners - Introduction (En)"

**Comment by valerydluski** [comment]
fixed
