### ISSUE TITLE
roadmap mismatch

### ISSUE THREAD

**Issue by idbttp** [rolling-scopes-school/tasks#1294]
if we open main [roadmap](https://github.com/rolling-scopes-school/tasks/blob/master/roadmap.md#%D1%8D%D1%82%D0%B0%D0%BF%D1%8B-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BA%D1%83%D1%80%D1%81%D0%B0), which is located on rss [tasks repo](https://github.com/rolling-scopes-school/tasks#%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0-%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F), it will be very different from the one that we have in our [curriculum](https://github.com/rolling-scopes-school/tasks/tree/master/stage1#-topics-covered)
maybe that's only because roadmap hasn't been updated/translated yet

p.s. for some reason i can't add any assignees to this issue
p.p.s. i can help with translation if needed

**Comment by valerydluski** [comment]
Thank you for the issue, a translation won't be enough; we are currently developing new roadmaps.
