### ISSUE TITLE
[2023Q4]: Week-9 Task: Translation HTML Builder

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1334]
## Description:
The "HTML Builder" task, an integral part of our Stage 1 curriculum, needs to be translated into English. This translation is essential to make the task accessible to a wider audience of students and to ensure consistency across our curriculum.

## Objectives:
- To translate all content of the "HTML Builder" task into English, maintaining the essence and technical accuracy of the original content.
- To ensure that the translated task is clear, understandable, and accessible for English-speaking students.

## Link to Task:
[HTML Builder Task](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder)

## Tasks:
1. **Translation of Task Description and Guidelines**:
   - Translate the task’s objectives, instructions, and any guidelines into English.
   - Ensure that technical terms and coding-related language are accurately translated.

2. **Translation of Supporting Materials**:
   - Translate any additional materials or resources provided with the task.
   - Maintain the format and structure of the original materials for consistency.

3. **Review of Translated Content**:
   - Have the translated content reviewed by native English speakers who are also knowledgeable in web development and HTML.
   - Ensure the translation is not only linguistically accurate but also contextually relevant to the subject matter.

## Acceptance Criteria:
- The "HTML Builder" task is fully translated into English, with all components including descriptions, guidelines, and additional materials accurately conveyed.
- The task maintains its educational effectiveness and is well-received by English-speaking students.

**Comment by haslie22** [comment]
PR is [here](https://github.com/rolling-scopes-school/HTML-builder/pull/2)
