### ISSUE TITLE
[2023Q4]: Week-2.3 Task: Development of a Comprehensive Date Manipulation Task Set in JavaScript

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1364]
## Description:
We aim to create a series of tasks, each varying in complexity, that focus on working with JavaScript's Date object. The purpose of these tasks is to deepen students' understanding and skills in manipulating and utilizing dates in JavaScript, reflecting the hidden complexities and common use cases in real-world applications.

## Objectives:
- Develop a task set that covers fundamental to advanced manipulations of the Date object in JavaScript.
- Ensure the tasks challenge students to think critically and apply best practices in date manipulation.
- Provide a range of tasks that demonstrate the versatility and intricacies of the JavaScript Date object.

## Tasks:
1. **Task Design**:
   - Design tasks of varying complexities, from basic date retrieval and formatting to more complex calculations and manipulations.
   - Ensure each task focuses on practical and common real-world scenarios involving dates.

2. **Reference Existing Materials**:
   - Utilize the tasks in [core-js-101 Date Tasks](https://github.com/valerydluski/core-js-101/blob/master/src/04-date-tasks.js) as a basis for complexity and variety.
   - Adapt and expand these tasks to cover a wider range of date-related operations.

3. **Instruction and Documentation**:
   - Write clear and concise instructions for each task.
   - Provide contextual information where necessary to assist students in understanding the practical applications of the skills being tested.

## Expected Outcome:
- A comprehensive set of JavaScript date manipulation tasks, ready for student engagement.
- The tasks should effectively challenge students and enhance their understanding and skills in working with the Date object in JavaScript.

**Comment by MikAleinik** [comment]
https://github.com/rolling-scopes-school/core-js-dates

**Comment by MikAleinik** [comment]
[PR#1](https://github.com/rolling-scopes-school/core-js-dates/pull/1)
