### ISSUE TITLE
Не работает ссылка в файле HTML-CSS-self-ru.md

### ISSUE THREAD

**Issue by olgalatkina** [rolling-scopes-school/tasks#138]
В файле HTML-CSS-self-ru.md не работает ссылка в разделе "Как сдать задание?", ведёт на ненайденную страницу (код 404).  

Адрес проблемного файла:  
* https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-1/HTML-CSS-self-ru.md

Не работающая ссылка:  
* https://app.rs.school/course/submit-task?course=rs-2019-q3

**Comment by mikhama** [comment]
Ссылка исправлена на верную.
@olgalatkina спасибо за issue

**Comment by olgalatkina** [comment]
@mikhama  
Thank you for fixing this broken link!  
So I am closing my pull request #139
