### ISSUE TITLE
[2023Q4]: Week-2.1: Translation and Update of "TypeScript Basic" Module

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1418]
## Description:
The "TypeScript Basic" module, a crucial component of our Stage 2 curriculum, needs to be translated into English and updated to reflect the latest advancements and best practices in TypeScript programming.

## Objectives:
- To translate all materials related to the "TypeScript Basic" module into English, ensuring it is accessible to a wider student base.
- To review and update the module content to align with the current version of TypeScript and incorporate modern development practices.

## Link to Module:
[TypeScript Basic Module](https://github.com/rolling-scopes-school/tasks/tree/master/stage2/modules/typescript-basic)

## Tasks:
1. **Translation of Module Content**:
   - Translate all instructional content, including tutorials and resources, into English.
   - Ensure the technical terminology and concepts are accurately translated.

2. **Review of Module Content**:
   - Conduct a thorough review of the module to identify any outdated information or practices.

3. **Incorporating New Material**:
   - Add new content or resources that cover recent developments in TypeScript.

## Expected Outcome:
- A fully translated and updated "TypeScript Basic" module in English.
- The module should provide a comprehensive and up-to-date understanding of TypeScript, suitable for learners at the specified stage of the curriculum.

**Comment by haslie22** [comment]
PR is [here](https://github.com/rolling-scopes-school/tasks/pull/1423)
