### ISSUE TITLE
[2023Q4]: Week-2.2: Translation and Update of "TypeScript Advanced" Module

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1429]
## Description:
The "TypeScript Advanced" module, a vital component of our Stage 2 curriculum, requires translation into English and an update to ensure it aligns with the latest TypeScript features and best practices. This process is crucial to maintain the module's relevance and effectiveness for our English-speaking students.

## Objectives:
- To translate the entire "TypeScript Advanced" module into English, making it accessible to a broader audience.
- To update the module content to reflect the latest advancements in TypeScript, including new language features and advanced type handling.

## Link to Module:
[TypeScript Advanced Module](https://github.com/rolling-scopes-school/tasks/tree/master/stage2/modules/typescript-advanced)

## Tasks:
1. **Translation of Module Content**:
   - Translate content into English.
   - Ensure the technical terminology and advanced TypeScript concepts are accurately translated.

2. **Review and Update Module Content**:
   - Review the current module content to identify any outdated information or examples.
   - Update the module to include recent TypeScript developments, such as newer type features, utility types, advanced generics, and best practices in TypeScript programming.

3. **Incorporating New Material**:
   - Add new content or resources that cover the latest trends and methodologies in TypeScript.

## Expected Outcome:
- A fully translated and updated "TypeScript Advanced" module in English.
- The module should provide a comprehensive and current understanding of advanced TypeScript features and practices, suitable for learners at the advanced stage of the curriculum.

**Comment by haslie22** [comment]
PR is [here](https://github.com/rolling-scopes-school/tasks/pull/1444)
