### ISSUE TITLE
[2023Q4]: Week-2.2: Translation and Potential Update of "Migration: News API to TS" Task

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#1431]
## Issue Title:
Translation and Potential Update of "Migration: News API to TS" Task

## Description:
The "Migration: News API to TS" task, integral to our curriculum's focus on practical TypeScript application, requires translation into English and a review for updates. This task, which involves migrating JavaScript code to TypeScript, is crucial for teaching students how TypeScript can be implemented in real-world scenarios.

## Objectives:
- To translate the "Migration: New API to TS" task into English, making it accessible to a broader audience.
- To review and update the task to ensure it aligns with the latest TypeScript features and migration best practices.

## Link to Task:
[Migration: News API to TS Task](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md)

## Tasks:
1. **Translation of Task Content**:
   - Translate all instructions, guidelines, and descriptions associated with the "Migration: News API to TS" task into English.
   - Ensure that technical terms and TypeScript-specific concepts are accurately translated.

2. **Review of Task for Updates**:
   - Evaluate the task to ensure it aligns with the current version of TypeScript and contemporary migration strategies.
   - Identify areas where the task might be enhanced to include more recent TypeScript features or improved migration techniques.

3. **Content Update (if needed)**:
   - Update examples, scenarios, and instructions to reflect modern TypeScript usage and best practices for code migration.
   - Ensure the task remains challenging and relevant for students learning TypeScript.

## Expected Outcome:
- A fully translated and updated "Migration: News API to TS" task in English.
- The task should effectively teach students the practical aspects of migrating JavaScript code to TypeScript, reflecting the latest standards and practices in the industry.

**Comment by haslie22** [comment]
PR is [here](https://github.com/rolling-scopes-school/tasks/pull/1476)
