### ISSUE TITLE
Опечатки в макете singolo1 - "Inovative" вместо "Innovative", лишний пробел перед точкой

### ISSUE THREAD

**Issue by elushnikova** [rolling-scopes-school/tasks#150]
Решение Singolo Part 1 будет проверяться на pixel perfect, но в проверочном макете есть опечатки. Ссылка на директорию с заданием и макетами: https://github.com/rolling-scopes-school/tasks/tree/master/tasks/markups/level-2/singolo/part-1

### Опечатка 1
"Inovative" вместо "Innovative".
![singolo1-typo](https://user-images.githubusercontent.com/45839055/74306062-490f1080-4d83-11ea-821c-3b09aa100ec7.png)

### Опечатка 2
Лишний пробел перед точкой.
![singolo1-extra-space](https://user-images.githubusercontent.com/45839055/74307254-bc665180-4d86-11ea-9e87-6a3167af9bf2.png)

**Comment by dzmitry-varabei** [comment]
@elushnikova спасибо! в следующем наборе поправим
