### ISSUE TITLE
HTML academy

### ISSUE THREAD

**Issue by lolmaster277** [rolling-scopes-school/tasks#152]
Проверка дз не сработал для двух курсов Селекторы, часть 1 и Наследование и каскадирование. Видимо потому что последние задания платные и весь курс пройти не удается. мой id1374313

**Comment by amoebiusss** [comment]
@lolmaster277 это репозиторий с заданиями, этот ишью не относится к заданиям.

В дискорд-канале #announcements-2020q1 есть ответ на ваш вопрос.
