### ISSUE TITLE
task: не работает проверка Html Academy Account

### ISSUE THREAD

**Issue by kirill-efimov-sk** [rolling-scopes-school/tasks#153]
Не срабатывает проверка задания по id Html Academy Account. Все задания уже пройдены по id1269983

Описание ошибки
1. No Codecademy account provided 2. Htmlacademy. Required courses: ["ЗнакомствосНТМLиСSS","СтруктураНТМLдокумента","Разметкатекста","Ссылкииизображения","ОсновыСSS","Оформлениетекста","Знакомствостаблицами","Знакомствосформами","Селекторычасть1","Наследованиеикаскадирование"] / Passed courses: ["ЗнакомствосНТМLиСSS","СтруктураНТМLдокумента","Разметкатекста","Ссылкииизображения","ОсновыСSS","Оформлениетекста"] 3. Udemy. Required courses count: 1 / Passed course count: 0

https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-1/HTML-CSS-self-ru.md

**Comment by kirill-efimov-sk** [comment]
Дополнительно - почтовый ящик подтвержден давно, id выбран верный.
При переходе с [гита](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-1/HTML-CSS-self-ru.md) по ссылкам все курсы пройдены. Могу предоставить скриншоты.

**Comment by amoebiusss** [comment]
@kirill-efimov-sk это репозиторий с заданиями, этот ишью не относится к заданиям.

В дискорд-канале #announcements-2020q1 есть ответ на ваш вопрос.

**Comment by dzmitry-varabei** [comment]
@amoebiusss спасибо за твою помощь!
