### ISSUE TITLE
SongBird

### ISSUE THREAD

**Issue by aykuli** [rolling-scopes-school/tasks#155]
Может добавить в требованиях к таску:
- [ ] eslint. Без него код плывет, очень плохо читается. И даже если он есть, требование папку src не добавлять в .eslintignore (бывает и такое).
- [ ] требования по оформлению PR, как в 2-этапе. Может некоторые пришли на реакт не проходя этот этап, и не привыкли оформлять так, чтоб проверяющему было удобно проверять.
 - посчитать свои баллы.

**Comment by irinainina** [comment]
Можно и добавить. А зачем? Таск выполнен, сдан, проверяется. На следующий набор его выдавать нет смысла - сейчас в открытых репозиториях на гитхабе по запросу songbird сотни выполненных тасков - копируй любой.

**Comment by aykuli** [comment]
ну тогда да наверно. Я думала, еще будут выполнять.
Надо было такое issue открывать гораздо раньше) Ок, я тогда его закрою.
