### ISSUE TITLE
Singolo cross check: нет критериев проверки по работоспособности валидации полей формы/mailto ссылок

### ISSUE THREAD

**Issue by elushnikova** [rolling-scopes-school/tasks#170]
Ссылка на условия кросс-чека: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/markups/level-2/singolo/singolo-cross-check-1.md

В условиях есть критерий к наличию валидации, но нет критериев проверки этой валидации. Также есть критерий к наличию mailto ссылки, но нет требования к проверке этой ссылки.

Например, в работе N есть следующие ошибки:
1. Поле "Name" не пропускает моё имя - на нём висит регулярка с требованием указать 8 символов или больше. Имя с фамилией тоже не пускает - регулярка запрещает пробелы. В результате я не могу пользоваться формой.
1. Mailto ссылка имеется, но в `href` стоит другой емейл - к тому же невалидный, с двумя `@`. Получается, пользователь не может отправить письмо по этой ссылке.

За эти ошибки я не могу снижать баллы, так как они не прописаны в критериях. 

По факту вёрстка из **работы N** (нерабочая форма + кривой mailto) ударит по бизнесу сильнее, чем, скажем, вёрстка из **работы M**, где единственная ошибка - в двух местах расползшийся line-height на 3px. 

В моём кейсе пришлось ставить за работу N балл выше. Очень хотелось бы видеть критерии с учётом "стоимости" ошибок для бизнеса.

**Comment by MadaShindeInai** [comment]
Насколько я помню, критерии были : 
- идеально - 100% баллов
- есть недостатки - 50% баллов
- не сделано - 0 баллов

Сложная валидация e-mail не имеет смысла(если нет запроса у заказчика), т.к. email в наши дни может быть практически любым. Максимум -  проверить:  /символы/@/символы/./символы/
По остальным полям: 
телефон - символы + числа или просто числа;
имя/фамилия - символьная валидация не имеет смысла , разве что проверить введено ли хоть что-то;

**Итого**: на мой взгляд, наличие любой (хоть какой-то) валидации достаточно для выставления **100%** баллов студенту. Уточнять и описывать каждую мелочь в задании не стоит, т.к. это только усложнит восприятие.
