### ISSUE TITLE
Ошибка в тексте singolo-cross-check-2-ru.md

### ISSUE THREAD

**Issue by aleksandr-jasinski** [rolling-scopes-school/tasks#187]
> При этом нажимая на кнопку еще раз, картинка снова должна меняться. 

Картинка не нажимает на кнопку :-) 
В русском языке действия, обозначенные деепричастием и глаголом-сказуемым, должны принадлежать одному и тому же субъекту действия.

**Comment by Kamikozz** [comment]
Я бы на вашем месте самостоятельно сделал нужные изменения и открыл Pull Request на слияние
