### ISSUE TITLE
Problem connecting to websocket url

### ISSUE THREAD

**Issue by NataD** [rolling-scopes-school/tasks#231]
The connection to the url provided in the task (ws://st-chat.shas.tel) cannot be established. The connection status remains pending for some time, and then it disconnects (error message: `Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`). I get the same result while testing the connection via online tools (https://www.websocket.org/echo.html). 
Could someone please verify if the connection to the provided url can actually be achieved?

Task link: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/chat.md

**Comment by Shastel** [comment]
Fixed, thanks
