### ISSUE TITLE
Semantic error in 'codewars-stage-1.md' task description.

### ISSUE THREAD

**Issue by EgorNedelko** [rolling-scopes-school/tasks#271]
![issue-1](https://user-images.githubusercontent.com/43146681/94344417-e32c7c00-0027-11eb-8690-d3b92e65e7fc.PNG)
It is not possible to use **'at all'** in a positive sentence. 
It can only be used in questions and negative sentences. 
In this particular case **'in total'** construction will be much more suitable.

**Comment by dzmitry-varabei** [comment]
спасибо!
