### ISSUE TITLE
Подготовка тестов

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#339]
Ищу желающих помочь с разработкой/подбором тестов для следующих тем: 

## Stage#0
- [Основы работы с Chrome Dev Tools и VS Code](https://github.com/rolling-scopes-school/tasks/blob/master/stage0/modules/basic-tools/README.md)
- [Дорожная карта JS/FE Разработчик](https://github.com/rolling-scopes-school/tasks/tree/master/stage0/modules/js-fe-developer)
- [DOM API](https://github.com/rolling-scopes-school/tasks/tree/master/stage0/modules/dom-api)
- [DOM Events](https://github.com/rolling-scopes-school/tasks/tree/master/stage0/modules/dom-events)
- [CSS Positioning & Flexbox](https://github.com/rolling-scopes-school/tasks/tree/master/stage0/modules/css-positioning)

## Stage#1
- [HTML Forms & Validation](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-form)
- [Preprocessors. SASS](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/sass)
- [Media Queries](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/media-queries)
- [Типы данных в JS](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/js-basics)
- [JS Scope & Functions](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/functions)
- [CSS Grid](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/css-grid)
- [Figma](https://github.com/rolling-scopes-school/tasks/tree/master/stage0/modules/figma)
- [Web Storages](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/web-storage)
- [Webpack](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/webpack)
- [Async JS](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/async)
- [JS Classes & Prototypes ](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/classes-prototypes)
- [ChromeDevTools](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/chrome-devtools)
- [Events](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/events)
- [Event Loop & Animation](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/eventloop-animation)
- [DOM Api](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/dom-api)
- [JS Evolution](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/js-evolution)
- [RWD](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/responsive-web-design)

**Comment by pavelrazuvalau** [comment]
Беру следующие темы:
- Типы данных в JS
- JS Scope & Functions
- Async JS
- JS Classes & Prototypes

**Comment by helenakrasnova** [comment]
Тесты в **Done**:
- Основы работы с Chrome Dev Tools и VS Code
- Дорожная карта JS/FE Разработчик
- DOM API
- DOM Events
- CSS Positioning & Flexbox
- Типы данных
- JS Basics
- JS Scope & Functions
- CSS Grid
- Figma
- Preprocessors. SASS
- Media Queries + Responsive
- HTML Forms & Validation
- Webpack
- Async JS
- JS Classes & Prototypes
- Event Loop + Animation
- Web Storage
- Testing
- HTTP/HTTPS
- RESTful API

Тесты в **To be done**:
- OOP Basics
- Typescript basic
- Typescript advanced
- JS Error Handling
- Functional Programming Basics
- Scrum/Kanban
