### ISSUE TITLE
Stage #1 TODO list

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#348]
### Неделя #9
- Модуль: Modules in JS
- @ai297 [Модуль: Webpack](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/webpack/)
- [Модуль: CSS Preprocessors. Sass](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/sass/)
- @irinainina Проект Momentum. Продолжение. 

### Неделя #10
- @rkhaslarov [ShortTrack Tasks](https://github.com/rkhaslarov/rs-school-short-track-2021)
- @aykuli [Git Recap](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/git-recap/)
- @amoebiusss  [Проект Self-introduction](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder/)
- [Проверка уровня базовых знаний. Тесты и задачи по алгоритмам и структурам данных](algorithms) 

### Неделя #11
- @EvgeniiMal [Проект HTML-Builder](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder/)

### Неделя #12
- @jegius [Модуль: Clean Code](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/clean-code/)
- @aykuli [Модуль: Web Storage](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/web-storage/)
- @jegius  Проект на СoreJS

## Задания
- новые алгоритмические таски
- новые таски для rs short track 

## Распределить модули среди тренеров
1. Mikalai Shchakatsikhin Hirurgo
2. ~~Айнур aykuli~~
3. Виктор Ковалев
4. ~~Sergey Shalyapin~~
5. ~~Pavel Razuvalau~~

**Comment by aykuli** [comment]
Неделя #1
    @aykuli Модуль "Знакомство с системой контроля версий Git"

Неделя #7
     @aykuli Модуль: Chrome DevTools

Неделя #8
    @aykuli Модуль: JavaScript. Classes & Prototypes

Неделя #10
    @aykuli Git Recap

Неделя #12
    @aykuli Модуль: Web Storage

Chrome DevTools,  JavaScript. Classes & Prototypes - у меня есть готовые презентации,
git - просто люблю гит,
Web Storage - может узнаю что-то новое для себя )

**Comment by dzmitry-varabei** [comment]
@aykuli спасибо! пометил!

**Comment by dzmitry-varabei** [comment]
@DimaBLR Задание [Custom jQuery](https://github.com/rolling-scopes-school/dimablr-JSFE2021Q1/tree/RS-School/custom-jquery)

**Comment by aykuli** [comment]
Могу взять еще Модуль "Chrome Dev Tools, VS Code, Terminal" - я такое уже проводила. Могу повторить. На следюущей неделе.

**Comment by aykuli** [comment]
Как я поняла, по срванению с 7 неделей, тут надо показать необходимый минимум

**Comment by dzmitry-varabei** [comment]
@aykuli да, необходимый минимум
Записал за тобой!
