### ISSUE TITLE
Обновить список тем для corejs interview

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#352]
@valerydluski обновить https://github.com/rolling-scopes-school/tasks/blob/master/tasks/interview-corejs.md
@dzmitry-varabei проверить актуальность модулей stage#1 & 2 в соответствии с новым списком

**Comment by valerydluski** [comment]
@jegius & @AlreadyBored  проверить актуальность новых тем вопросов
@jegius & @valerydluski  подумать как разбить все темы на несколько этапов
