### ISSUE TITLE
Museum-adaptive

### ISSUE THREAD

**Issue by Bulation** [rolling-scopes-school/tasks#396]
Предлагаю добавить в раздел "Соответствие вёрстки макету" следующий абзац: "При проверке верстки на разрешениях 1024px, 768px и 420px переключите тип девайса с desktop на mobile в верхней панели device toolbar ". Благодаря этому уберется вертикальный скролл из-за которого фактическое разрешение экрана становилось на 17 пикселей меньше выставленного в верхней панели

**Comment by irinainina** [comment]
Привет. Добавлю. Раньше в этом не было необходимости потому что тип Mobile это значение по умолчанию
