### ISSUE TITLE
RS School. Недостаток рекламы

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#399]
Собираю идеи о том, как можно решить проблему с недостатком рекламы курсов RS School.

- Где и в каком виде вы бы хотели видеть рекламу курсов RS School?
- Как было-бы удобнее ее шарить?

**Comment by dzmitry-varabei** [comment]
- Cоздать отдельный read-only канал в Telegram для анонсов старта курсов
- Обновить описание школы на канале https://www.youtube.com/c/RollingScopesSchool/about
- Сделать стандартный шаблон подписи к роликам школы на YouTube. Для того, чтобы под каждым роликом была информация о том, как попасть на курсы rs school.

**Comment by irinainina** [comment]
По результатам опроса
- 60 студентов узнали о курсе от друзей, родных, знакомых, коллег по работе
- 40 из разных источников в интернете
- 20 из сайта epam

То есть основной источник привлечения на курс - сарафанное радио. Нужно делать упор на наших студентов, которые учатся сейчас, стремиться, чтобы они были счастливы, помогать, поддерживать, поощрять, делиться историями успеха, и они пригласят к нам своих друзей и знакомых, особенно, если мы их об этом попросим.

Информацию о курсе в интернете можно распространять тоже через студентов. Например, статьи на публичных ресурсах, которые они пишут о своих финальных проектах.

Что касается epam, с ними нужно как-то координировать действия, чтобы они не рассылали приглашения на уже закончившийся курс 2021q1, чтобы при регистрации на сайте epam, студента уведомляли о необходимости регистрации в rs app и в дискорде.

Ещё один источник информации  о курсе - it-вузы и колледжи. Из 21 студента, проходившего опрос, ни один не ответил, что узнал про rs-school в своём учебном заведении.

**Comment by dzmitry-varabei** [comment]
@irinainina хорошо, спасибо большое!
