### ISSUE TITLE
Тест для новичков в RSSchool

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#43]
В наборе RSSchool 2018Q3 был такой фидбек:
```
Я б предложил перед началом занятий, что б каждый участник курсов 
проходил тест по тому, как учится и что делать в школе. К примеру один
 из вопросов мог бы звучать: "надо ли связывать аккаунты codeacademy и
 padawans и должно ли в padawans что-то отображаться?"  выглядит 
может это и смешно но лишние +100500 вопросов и обращений
 такой тест смог бы помочь избежать. Т.е взять вопросы из FAQ 
и по ним и провести тест. 
```
 Если у вас идеи, пожелания, комментарии или предложения по вопросам и вариантам ответов для такого теста  - пишите прямо тут.

**Comment by dzmitry-varabei** [comment]
Вариант вопроса: Что такое RS Short Track?

Варианты ответов: 
а) Скоростной бег на коньках на короткой дорожке
b) Отдельная учебная программа The Rolling Scopes, заменяющая собой обучение в #stage2 и #stage3 RSSchool основного набора.

**Comment by olgaluk** [comment]
Добрый день! Я нахожу весьма полезным проведение такого теста, только хотелось бы внести ряд предложений. Я считаю, что перед проведением такого теста, необходимо разместить информацию, которая будет включать ответы на вопросы, в одном месте. Так как часть ответов на многие вопросы давалась на вебинаре, часть в чате, а часть была на страницах сайта школы. Страница сайта школы https://school.rollingscopes.com/schedule-info.html уже содержит ряд вопросов с ответами, которые можно включать в этот тест, но ее необходимо местами дополнить. Один из них - "Что из себя представляет "Тест по основам HTML/CSS"?". Из этого пункта можно сделать несколько вопросов для теста:
1) Обязательно ли проходить "Тест по основам HTML/CSS" два раза? (на странице сайта школы внести уточнение по этому вопросу);
2) Сколько минут длится тест? (не требуется уточнение на сайте, ответ уже есть);
3) Если отправил форму с тестом на 1 мин позже, будет ли засчитан тест?
Далее считаю полезным включение вопросов в тест по "штрафам" за несвоевременную сдачу тасков. Эта информация также уже присутствует на сайте школы в полном объеме, так что не нуждается в уточнении. Примеры вопросов:
1) Вы не успели к дедлайну, выполняя таск  из категории "CodeJam", какое максимальное количество баллов за этот таск вы получите?

**Comment by mikhama** [comment]
@dzmitry-varabei Отличная идея! Предлагаю такой тест делать перед (или в процессе) каждого из этапов. Причем учитывать прохождение теста для перехода на следующие этапы. Например, если ответил правильно на 50% или более + другие условия для перехода на следующий этап соблюдены - студент переходит на следующий этап, а иначе - нет.

Проштудировал старый чат questions в gitter'е. Предлагаю такие вопросы для рассмотрения:

**1. Один из вопросов, как не странно, который задают даже на третьем этапе:**

*Ребята, дайте ссылку на расписание.*

Как вариант вопроса:
- *Вставьте в форму ссылку на расписание.*

Возможно кто-то подумает над тем, чтобы сохранить ссылку на него себе в закладки.
Еще вопросы к теме ссылок (как по мне важно один раз запомнить или сохранить ссылки на необходимые ресурсы, чтобы потом каждый раз не задавать один и тот же вопрос: А где будет запись?, и т. п.):
- *Вставьте в форму ссылку на репозиторий школы.*
- *Вставьте в форму ссылку на YouTube-канал Imaguru.*
- *Вставьте в форму ссылку на YouTube-канал Rolling Scopes.*

**2. Как репозиторий склонить к себе на компьютер?**
а) А что такое репозиторий? Нас этому еще не учили.
б) Нужно нажать кнопку Fork на github'e, а затем на кнопку Clone or Download, скопировать ссылку и воспользоваться командой git clone [link-to-repo].

**3. Можно ли будет пересдать задание в RS Padawans?**
а) Да.
б) Можно, но до дедлайна.
в) Нельзя.

**4. Должны ли в RS Padawans быть видны бэджи с Codeacademy?**
a) Да.
б) Нет.

**5. Как из RS Padawans убрать решенное задание и добавить новое решение?**
а) Никак. То что один раз было засабмитано уже не изменить.
б) Лучше спросить в канале questions.
в) Коммитишь новое решение, делаешь git push и нажимаешь кнопку сабмит.

**6. Где будет ссылка на тест по основам HTML/CSS?**
а) В канале announcements, как и вся важная информация.
б) В канале general.
в) Придет на почту, указанную при регистрации в RS Padawans.

**7. Как правильно скопировать код, чтобы тебе помогли разобраться почему он работает не так как ожидалось?**
а) Использовать markdown, а лучше выложить проблемную функцию на https://codepen.io/ или другой подобный сервис.
б) Просто скопировать код в чат, другие люди смогут скопировать его и запустить у себя.
в) Сделать скриншот кода и выложить ссылку в чат.

**8. Сколько людей проходит на этап собеседований во второй этап? (цифру правильного ответа не забыть скорректировать в зависимости от кол-ва менторов)**
а) ~490.
б) ~1000.
в) ~100.

**9. Обязательно ли проходить два теста по основам HTML/CSS?**
а) Да.
б) Можно пройти только один, в скор пойдет лучшая оценка.

**10. А запись будет?**
а) Все лекции на вебинарах, а также лекции в Имагуру по возможности записываются.
б) Нет.

**11. Как определеить какая kata уже решена в Codewars, а какая еще нет?**
a) Посмотреть в профиле (те, что с пометкой completed - решены) или использовать тулу от @auseika https://auseika.github.io/kata-scan/.
б) Те задания, у которых кнопка называется Train Again - решены.

**12. Как работать с приватным репозиторием?**
а) Делать все таски в master-ветке.
б) Создавать для нового таска папку и ветку с его названием.
в) Создавать для нового таска ветку с его названием.

**Comment by JuliaMV** [comment]
**13. Что делать если не получается попасть на CodeJam или Test?**
а) Написать организаторам с просьбой перенести или провести в индивидуальном порядке.
б) Пропустить и стараться выполнить остальные задания на максимальный бал.

**Comment by davojta** [comment]
**14. Что делать, если скор не обновлен / вам не выделен ментор для собеседования?**
а) написать в любой канал школы с вопросом
б) прочитать канал announcement и если нет объявлений, спросить своего ментора или написать в feedback форму школы. 
в) написать в личные сообщения Dzmitry Varabei

**Comment by davojta** [comment]
**15. Что делать, если вы всё делаете правильно, но у вас что-то не получается?**
а) написать в канале вопросов что у вас ничего не получается без пояснений, что вы уже попробовали и в чем собственно проблема
б) сделать минимальный пример на jsfiddle / codepen, привести список уже проверенных вариантов и попросить помочь в канале вопросов

**Comment by JuliaMV** [comment]
**16. Что нужно делать перед тем как задать вопрос в чате?**
a) Ничего не делать, сразу написать и ждать пока кто-нибудь ответит.
б) Попробовать загуглить вопрос на английском языке.
в) Прочитать предыдущие сообщения в чате, может быть этот вопрос задавали и на него уже есть ответ.

**Comment by Sijioth** [comment]
**17. Подходят ли результаты теста по английскому с training.by?**
а) Нет, не подходят.
б) Да, но надо будет пересдать.
в) Да, подходят.

**Comment by Sijioth** [comment]
**18. Куда отправлять скрин с результатами теста по английскому?**
а) В личные сообщения Dzmitry Varabei.
б) В личные сообщения своему ментору.
в) В личные сообщения Илону Маску.

**Comment by Sijioth** [comment]
19. Можно ли работать в EPAM на полставки?
а) Нет.
б) Да.
в) Зависит от обстоятельств.

**Comment by davojta** [comment]
@Sijioth @JuliaMV @mikhama нет ли у вас желания сделать тест в гугл формах?) Я бы проверил / менторил если надо )
