### ISSUE TITLE
Описание видеозаписей для цикла RS Pair Programming 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#44]
Сейчас есть описание только части занятия из цикла RS Pair Programming  - https://github.com/rolling-scopes-school/lectures/blob/master/lectures/rs-online-development.md

Видеозаписи в плейлисте - https://www.youtube.com/watch?v=pzRiqBZh-O4&list=PLe--kalBDwjhxK4bQHD8zpAp-RuhCHu7k

Если, кто-то может сделать описание одного или нескольких занятий, оставляйте текст в комментариях к issue или присылайте PR.

Спасибо!

**Comment by JuliaMV** [comment]
### #6 Webpack

Запись - https://youtu.be/eT3vHKYmr-c
- подключение и файл конфигурации
- loaders
- plugins
- webpack-dev-server
- git husky
               
### #7 MongoDB
Запись - https://youtu.be/TWUiiIUWIN8

- Robo 3T
- mongoose
- модели, схемы и методы

**Comment by Luffi2539** [comment]
#3 Calculator

Запись - https://youtu.be/4psWjsQOSAQ

* Создание сервера на Node JS (Express)
* Перенос логики калькулятора с фронт-энда на бэк-энд
* Eslint
* npm vs yarn
* package.json что это за файл и зачем он нужен

**Comment by dzmitry-varabei** [comment]
@JuliaMV @Luffi2539  спасибо!
