### ISSUE TITLE
Stage 0. Модуль "Знакомство с Codewars"

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#444]
Есть предложение добавить в stage#0 модуль "Знакомство с Codewars".

Примерное содержание:
- знакомство с платформой
- типовые проблемы при решении задач
- как дебажить задачи,
- советы по решению задач
- лайв кодинг пары задач
- как сабмитнуть результат в RS APP

Нужен ли такой модуль в stage#0?
Были ли у вас какие-либо проблемы с codewars? 
Буду рад любым вашим советам и комментариям тут

**Comment by Loktysh** [comment]
Уже существуют стримы с решением типовых алгоритмических задач, есть большой стрим Жана, где он решает задачи оттуда.
В самом таске задач
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/Codewars1-2021Q3.md
снизу есть материалы, а интерфейс сайта достаточно простой.

**Comment by Dairin-dei** [comment]
Лично мне бы такой модуль очень помог. Особенно про тесты и дебаг. Стримы у Жана интересные, но для меня часто очень сложные, хотя конкретно этот я не смотрела, к сожалению.

**Comment by Diluks93** [comment]
Я считаю, что **нужен**:
 * Многие новички сталкиваются с проблемой номер один это решить первую задачку для входа на площадку codewars. 
 * Стоит объяснить, что такое "kyu".
 * Как распределены задачи по сложности.
 * Что значит версия node или изучаем язык.
 * Сталкивался с вопросами _(касается применения # когда используем приватные методы)_ "почему эта штука (#) не работает, хоть в документации по java script написано, что должна?". В этом случае просто и банально объяснить, что каты могут уже автором не поддерживаться и использовать надо то, что было определено в ES6
 * Дополнительно, считаю стоит сказать, что многие (не все конечно), не понимают требований задания, что по итогу от нас ожидают. В этом случае решение - это либо спрашивать в discord, либо методом проб и ошибок искать в тестах ожидаемые результаты. 
 * Может будет актуально _(часто встречаю вопрос "почему в IDE логика / функция работает, а вставляю в codewars и там всё ломается и не работает?")_ тоже со старта новичкам объяснить, что это codewars и не стоит ожидать, что код в IDE будет работать также как и в codewars _(возможно я тяжело объяснил, но было такое, что не работало)._ 
 * Обязательно следует отметить, чтобы после решения изучали код предоставленный в **Best Practices** и старались не подсматривая реализовать его _(так я считаю можно быстрее изучить новые фичи ES6 и далее)._
 * Некоторые каты содержат в тестах строки закомментированного кода об этом тоже стоит сказать. 
**Модуль однозначно нужен.**

**Comment by Irina-coud** [comment]
Спасибо, что делаете обучение более комфортным! Особенно это важно для новичков!
Могу сказать, что когда я в первый раз увидела задачи, у меня был шок. Для новичка такой вводный модуль по кодварс будет очень полезен. Мне его в своё время не хватало!)

**Comment by pnv13** [comment]
Нужен! Как и любой другой подобный модуль, он поможет новичку на старте.

**Comment by chagins** [comment]
Я думаю, что лишним данный модуль однозначно не будет. Ведь это stage0! :+1:

**Comment by zzhanna** [comment]
Я как человек , пришедший с нуля, скажу , что и модуль нужен и видео обучающее, чтоб прям пошагово , это был такой квест для меня понять , как и что там делать). Да, даже регистрация там и то нужен был Гугл .

**Comment by PiachkoAliaksey** [comment]
Нужен такой модуль, очень бы помог в решении последующих задач)

**Comment by Katekarri** [comment]
как человек изучающий все реально с 0 всеми руками за такой модуль

**Comment by Luffi2539** [comment]
В модуль с начальными заданиями будет добавлена запись лекции с подробным разбором того что и как необходимо делать
