### ISSUE TITLE
Перевести описание тасков на английский язык 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#45]
Таски - https://github.com/rolling-scopes-school/tasks/tree/2018-Q3/tasks
Если вы перевели какой-нибудь таск, создавайте, пожалуйста, PR в этот репозиторий. 

Спасибо!

**Comment by dzmitry-varabei** [comment]
Спасибо @AntiHero за 4 PR!

**Comment by PavalEscoba** [comment]
Перакладаць трэба ж ня ўсе заданні? 
Як вызначыць тыя, якія сапраўды трэба перакласці?

**Comment by davojta** [comment]
@PavalEscoba можна спачатку перакласці заданні якія былі у 2018q3, пасля тыя што у 2019q1

**Comment by PavalEscoba** [comment]
Для тых, хто хоча паперакладаць створаная размова ў Дыскордзе/
Those who want to translate tasks please feel free to join our Discord channel:
https://discord.gg/2WzqBbu

**Comment by davojta** [comment]
@PavalEscoba а чаму не у агульнай группе RS ?

**Comment by dzmitry-varabei** [comment]
@PavalEscoba спасибо за помощь! может ты не против ревьювать все PR связанные с переводами?

**Comment by PavalEscoba** [comment]
Добра. Згодзен.

**Comment by dzmitry-varabei** [comment]
@PavalEscoba  выслал инвайт
