### ISSUE TITLE
stage 1 2022q1

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#453]
- [x] 1. Забрать модули по структурам данных из stage0 в stage1.
- [x] 2. Figma переделать модуль
- [x] 3. Пересмотреть порядок и время выдачи алгоритмических/codewars задач.
- [x] - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/Codewars1-2021Q3.md
- [x] - https://github.com/AlreadyBored/basic-js
- [x] - https://github.com/AlreadyBored/basic-js-ds
- [x] - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/Codewars2-2021Q3.md
- [x] 4. Пересмотреть порядок модулей
- [x] 5. Переделать модуль https://github.com/rolling-scopes-school/tasks/tree/master/stage0/modules/js-fe-developer

**Comment by dzmitry-varabei** [comment]
3. Пересмотреть порядок и время выдачи алгоритмических/codewars задач.
- https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/Codewars1-2021Q3.md
- https://github.com/AlreadyBored/basic-js
- https://github.com/AlreadyBored/basic-js-ds
- https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/Codewars2-2021Q3.md

**Comment by dzmitry-varabei** [comment]
1) Положить копию модулей stage0 (которые дублируются в stage#1) в https://github.com/rolling-scopes-school/tasks/tree/master/stage1.
2) Вернуть тесты https://github.com/rolling-scopes-school/tasks/commit/24384958a1c34810f0bac5c690d1ae3e25c7b7c4

**Comment by dzmitry-varabei** [comment]
- Подумать что можно выбросить
