### ISSUE TITLE
Задачи к модулю fp-basics

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#455]
Вернуть https://github.com/rolling-scopes-school/tasks/commit/fd3019c4df2f2e917a1d1c0b0039af87ac5edb6c#diff-d34817bd2c48541e8c235bf44d0d8f5414a625c640ccb02fbb9f2d3e9b0b4cc5 и, по возможности, добавить пару новых

**Comment by natein** [comment]
Добавила несколько задач к тем, что были удалены из Stage1
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/Codewars3-2021Q3.md
Посмотри, достаточно ли задач сейчас.

**Comment by dzmitry-varabei** [comment]
@natein все отлично! спасибо!

**Comment by dzmitry-varabei** [comment]
СС @valerydluski

**Comment by valerydluski** [comment]
https://www.codewars.com/kata/uncurrying
может бета не нужно включать в список?

**Comment by natein** [comment]
С бетами всё в порядке, они проблем не доставляют. А эта задачка хорошая, мне её жалко выбрасывать. :)

**Comment by valerydluski** [comment]
Тогда все окей
