### ISSUE TITLE
NodeJs. Задание по тестированию 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#463]
Добавить к модулю https://github.com/rolling-scopes-school/tasks/tree/master/stage2/modules/testing
небольшое задание (до 10 часов на выполнение). Как вариант, можно по аналогии с заданием на миграцию JS кода на TS (есть готовое приложение, надо добавить тесты).

**Comment by dzmitry-varabei** [comment]
@jegius Как будет время посмотри, пожалуйста, https://github.com/emilybache/GildedRose-Refactoring-Kata

**Comment by AlreadyBored** [comment]
Testing task is implemented
https://github.com/AlreadyBored/basic-testing
