### ISSUE TITLE
Синтаксическая ошибка 

### ISSUE THREAD

**Issue by Hristick** [rolling-scopes-school/tasks#467]
Порядок работы пункт 4 : Вместо GitHub написано **CitHub**

**Comment by AlexanderBychyk** [comment]
Тоже заметил эту опечатку 😀

**Comment by irinainina** [comment]
Спасибо за внимательность. Думаю, это не единственная опечатка в описании тасков. Было бы хорошо проверить описание тасков и исправить в них все ошибки.

**Comment by Hristick** [comment]
Буду стараться сообщать , если хватит внимательности 😉
  
>Понедельник, 27 декабря 2021, 13:51 +03:00 от Irina ***@***.***>:
> 
> 
>Спасибо за внимательность. Думаю, это не единственная опечатка в описании тасков. Было бы хорошо проверить описание тасков и исправить в них все ошибки.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <rolling-scopes-school/tasks/issues/467/1001504921 @ github . com> 
 
 
С уважением,
Владимир Христофоров
***@***.***

**Comment by dzmitry-varabei** [comment]
@Hristick @irinainina всем спасибо!
