### ISSUE TITLE
Stage #0: CV#1. Markdown & Git 

### ISSUE THREAD

**Issue by TavaniX** [rolling-scopes-school/tasks#473]
Добрый день.

https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/git-markdown.md
В описании Порядка работы в п.6 ошибка:

![1](https://user-images.githubusercontent.com/39880369/146680916-3fd23f13-46ec-44f1-baf8-0e44f6b070b0.png)

Так как в советах по выполнению задания в п.7 написано вставить ссылку в файл README.md, который находится в ветке main, а не в ветке gh-pages (она будет создана позже):
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-hints.md

![image](https://user-images.githubusercontent.com/39880369/146681091-acb2d1bb-8809-4d19-aee6-7a32fcdc7f42.png)

Поэтому считаю, что либо в требованиях, либо в советах по выполнению есть опечатка в том, в какой ветке добавлять ссылку в README.md файл.

**Comment by TavaniX** [comment]
похоже, что в советах по выполнению ошибка, т.к. в тех же советах по выполнению, но упрощенных тоже как и в самом задании написано, что надо в ветке gh-pages в файле ридми вставить сссылку (п.6)

https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-simple-hints.md

![image](https://user-images.githubusercontent.com/39880369/146685911-5c8871e9-b3d5-480f-b937-5bb58401e3e7.png)

**Comment by irinainina** [comment]
Привет. Советы не являются частью задания. Их создал студент-активист, и искать в них неточности нет смысла. В этот раз он советы поправил, но на будущее, используйте советы только в той мере, в которой они помогают в выполнении задания. Если советы не помогают - не используйте или напишите свои.
