### ISSUE TITLE
[Stage 0: CSS Positioning. Flexbox] Evernote содержит неправильные данные

### ISSUE THREAD

**Issue by agitaev** [rolling-scopes-school/tasks#486]
В допольнительных материалах для [CSS Positioning и Flexbox](https://github.com/rolling-scopes-school/tasks/tree/master/stage0/modules/css-positioning#%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8B) указана [ссылка на Evernote](https://www.evernote.com/shard/s368/client/snv?noteGuid=4346cdea-9386-4738-bfff-f9faafc05e94&noteKey=fb6ec76312f7111b&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs368%2Fsh%2F4346cdea-9386-4738-bfff-f9faafc05e94%2Ffb6ec76312f7111b&title=CSS%253A%2BFlexbox%2B%2528htmlacademy.ru%2529), где указано что **дефолтное значение** `align-self: stretch`:
 
![image](https://user-images.githubusercontent.com/23414386/147637236-dcadf754-22ff-47b2-8efa-69a828f2a84c.png)

Но на [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/align-self#formal_definition), [здесь](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) и [здесь](https://cssreference.io/property/align-self/) указаны что начальное значение для `align-self` является `auto`, а не `stretch`. 

Меня больше всего волнует вот что. В тесте по CSS Flexbox, был такой вопрос про дефолтное значение `align-self`. Вполне возможно что большинство студентов выбирали `stretch` как правильный ответ, что не является правильным на самом деле :)

Предлагаю несколько вариантов решения данной inconsistency:
1. Если автором текста в вышеуказанного Evernote является кто-то из организаторов RS School, а не посторонний человек, то внести поправки в пункт про `align-self` и проверить другие значения тоже
2. Если мы не имеем связь с автором текста с Evernote, то убрать его из списка дополнительных материалов

**Comment by Pereguda** [comment]
Похожая ситуация с justify-content:
developer.mozilla.org - normal
www.w3.org - flex-start
webref.ru - flex-start

и с align-items:
developer.mozilla.org - normal
www.w3.org - normal
webref.ru - stretch

**Comment by dzmitry-varabei** [comment]
@agitaev спасибо!
@Luffi2539 чекни и поправь пожалуйста

**Comment by Luffi2539** [comment]
оправил тесты, по поводу justify-content - оставил flex-start так как mdn ведет на спецификацию и в спецификации указан flex-start, похоже что на mdn косяк
![image](https://user-images.githubusercontent.com/43149261/153291908-a2f70fd1-0293-40af-8528-7e4a63a6b30d.png)
