### ISSUE TITLE
обновить rs-lang

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#490]
- [ ] вынести авторизацию в отдельный блок
- [ ] 2 мини игры
- [ ] Убрать фото при регистрации
- [ ] разобраться со словарем 
- [ ] Своя игра?
- [ ] Добавить лучшие приложения из https://irinainina.github.io/rs-projects/#React%202021q1
- [ ] убрать видео
- [ ] jобновить презентацию?
- [ ] Критерии: добавить ts и тд

**Comment by pavelrazuvalau** [comment]
- 2 мини-игры: "Спринт", "Аудиовызов"
- авторизация
- упрощенная тренировка слов
- статистика

**Comment by irinainina** [comment]
На четверть меньше времени по сравнению с предыдущим набором (был месяц, стало три недели) и на четверть меньше участников это почти вполовину меньшее количество человеко-часов на работу.
Дополнительно к перечисленному предлагаю
- убрать словарь и все связанные с ним требования
- убрать страницу статистики и все связанные с ней требования
- сократить количество мини-игр до трёх (две на выбор из перечисленных  + третью придумать самим)
- если скинете ссылку на файл с заданием могу внести предложенные правки и сделать PR

**Comment by valerydluski** [comment]
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-2/rs-lang/rslang.md

**Comment by irinainina** [comment]
Здесь у студентов вопрос возник https://discord.com/channels/516715744646660106/933732042208870431/936635577053364255
>  что именно нужно добавить на бэк? Написано возможность указать имя при регистрации, но в swagger в пост запросе users есть name

**Comment by pavelrazuvalau** [comment]
@irinainina 
> что именно нужно добавить на бэк? Написано возможность указать имя при регистрации, но в swagger в пост запросе users есть name
предлагаю пункт с бэкендом убрать
> Должны ли студенты дописывать бекенд?
Не должны. Логаут подразумевает, что токен и данные пользователя будут удалены с localStorage

**Comment by pavelrazuvalau** [comment]
Создан ПР
https://github.com/rolling-scopes-school/tasks/pull/525

**Comment by pavelrazuvalau** [comment]
Изменения вмержены. Всем спасибо!
