### ISSUE TITLE
Тест по основам git в первом этапе обучения RSSchool

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#50]
Предлагаем вопросы/ответы. 
Может быть есть ссылки на хорошие готовые тесты.
Буду рад любым вашим предложениям!

**Comment by Luffi2539** [comment]
По своему опыту опишу то, с чем столкнется начинающий:
В: Если я удалю файлы на компьютере что произойдет с ними в гите?
О: Они останутся в нетронутом виде и вы можете их восстановить на компьютере при помощи Git  pull

В: Что делает git clone
О: Создает копию репозитория в git на вашем компьютере

В: Последовательность комманд для записи изменений в git
O: 1) git add 2) git commit -m 'message' 3)git push origin master

Это пока все что пришло в голову, если что добавлю :)

**Comment by aleksei-bulgak** [comment]
Q: Вы работаете в коллегой в одной ветке(branch) одновременно. Ваш коллега сделал изменения и запушил их в удаленную ветку(git push origin branch). Каким образом вы пожете забрать изменения с сервера и замержить их в свою ветку?
A1: 
```
git stash
git pull --rebase
git stash apply
```

A2:
```
git add -A
git commit -m "feat: some commit message"
git fetch
git merge origin/branch
```
A3:
```
git stash
git fetch
git merge origin/branch
git stash apply
```

P.S. Возможно(Скорее всего) есть и другие правильные варианты ответа. Но сходу пришли только эти.

**Comment by aleksei-bulgak** [comment]
Q: Как выйти из VIM
A1: `:wq`
A2: `:q!`

**Comment by liOdama** [comment]
Какую последовательно действий вам нужно сделать для выполнения заданий первого этапа:
А1 git clone [репозиторий] - приступить к работе
А2 git pull [репозиторий] - приступить к работе
А3 Форкнуть репозиторий на свой github - git clone [репозиторий] - приступить к работе

Вы работаете над проектом в команде с другими разработчиками, ваш коллега смержил свою ветку с master веткой. С помощью какой команды будет правильнее всего получить обновлённые даные из удалённого репозитория:
A1 git pull
A2 git clone
A3 git merge

**Comment by davojta** [comment]
Что делает git add
1) посылает локальные изменение на сервер
2) вносит изменения в локальный репозиторий
3) вносит изменения ваших текущих файлов в специальное хранилище изменений для следующего коммита

**Comment by davojta** [comment]
Что делает git commit
1) посылает локальные изменения на сервер
2) вносит текущие подготовленные изменения в локальный репозиторий 
3) вносит изменения ваших текущих файлов в специальное хранилище изменений для следующего коммита

**Comment by Sijioth** [comment]
9. Верно ли утверждение:  `Git != GitHub` ?
а) Конечно да!
б) Конечно нет!
в) Правильно будет `Git === GitHub` !

**Comment by Sijioth** [comment]
**10. Можно ли использовать UI инструменты для работы с Git?**
а) Нельзя - за это ругают.
б) Можно, однако начать лучше с работы с консолью.
в) Да, можно.

**Comment by mikhama** [comment]
**11. Кто придумал GIT?**
а) Денис Ритчи
б) Стив Джобс
в) Дмитрий Воробей
г) Линус Торвальдс

**Comment by mikhama** [comment]
**12. Какой git-командой можно отправить локальные изменения на сервер?**
а) upload
б) pull
в) push
г) update

**Comment by mikhama** [comment]
**13. Отметьте все способы создания новой ветки с именем *new-branch* в репозитории:**
а) git branch new-branch
б) git branch -b new-branch
в) git checkout -b new-branch
г) git checkout new-branch

**Comment by Sijioth** [comment]
**14. Если Вы работаете в отдельном branch-е, то все коммиты на master-branch:**
а) автоматически подтягиваются с remote-сервера в local на Вашем branch-е.
б) никак не влияют на Ваш branch.
в) необходимо синхронизировать с Вашим branch-ем в новый branch, и продолжать работу уже в нем.

**Comment by Sijioth** [comment]
**15. Как избежать merge conflict?**
а) Никак. Просто делаем resolve и “#move_forward”!
б) Перестать работать с git, а перейти на svn или mercurial.
в) Спросить у ментора.
г) Работать только в master-branch и настроить auto-pull чтобы иметь самую свежую версию файлов в локали.

**Comment by Sijioth** [comment]
**16. Выберите варианты с “Bad commit naming”:**
а) `binary-tree/feature: implement traverse method`.
б) `initial commit`.
в) `moi pervyi kommit, ne rygaite silno PLZ ^_^`.
г) `binary-tree/fix: error int he empty tree`.
д) `new super-duper feature`.
е) `master/update: remove .trash files`.

**Comment by DimaDK24** [comment]
@Sijioth,
> **16. Выберите варианты с “Bad commit naming”:**
> а) `binary-tree/feature: implement traverse method`.
> б) `initial commit`.
> в) `moi pervyi kommit, ne rygaite silno PLZ ^_^`.
> г) `binary-tree/fix: error int he empty tree`.
> д) `new super-duper feature`.
> е) `master/update: remove .trash files`.

Commit naming is mostly is just a convention. It's too individually. Personally, I can spot only one (2 max) bad commit names here. I wouldn't like this to be added to the test.

And I guess it would be too hard for newbies. They are still unsure what is commit actually and what should be in its name.

**Comment by davojta** [comment]
@DimaDK24 i think the main point - try to point student attention to that topic in general

I see at least 3 bad commit message names (в, д, е ). b is discussable.

**Comment by Sijioth** [comment]
@davojta  @DimaDK24 
I suggest keeping the question. We could just make variants more simple, more obvious.
Like "1?adfnaposifhqoiwemoaifs" or "whoa!justcheckitmate!itsjustawesome!" or "just commit, nothing special".

**Comment by dzmitry-varabei** [comment]
@Luffi2539 @aleksei-bulgak @liOdama @davojta @Sijioth @DimaDK24 @mikhama 
Спасибо вам! 
Приглашаю поучаствовать в создании теста ["Clean Code"](https://github.com/rolling-scopes-school/tasks/issues/70)
