### ISSUE TITLE
Обновление учебной программы по Stage#3 React.

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#508]
https://github.com/rolling-scopes-school/tasks/blob/master/stage3/stage3-react.md

**Comment by ragingyngvarr** [comment]
**Что можно добавить к текущей программе:**
1. Для хорошего понимания различных фаз в Реакт-компонентах (render, pre-commit, commit) хорошо бы одно из первых заданий давать на классовых компонентах.
[диаграмма](https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/)
2. Далее этот же таск можно переписать используя [хуки](https://github.com/rolling-scopes-school/tasks/blob/master/stage3/stage3-react.md#react-4-lecture-hooks)
3. В идеале задания могут учитывать особенности хуков, я бы предложил сконцентрироваться на самых используемых:
3.1. useEffect и useLayoutEffect(как больше аналог componentDidUpdate)
3.2. почему useReducer + useContext !== Redux
3.3. useRef при использовании с объектами, которые не нужно обновлять при каждом ререндере
4. Таск по [Error Boundary](https://reactjs.org/docs/error-boundaries.html])
5. Понимание основ [Reconciliation](https://reactjs.org/docs/reconciliation.html). Реакт использует 2 предположения в своем алгоритме сравнения, которые должны быть известны разработчикам

**Что можно добавить как гайдлайны для менторов на этапе командной задачи:**
Неплохо было бы давать студентам общие паттерны Реакта (часть уже есть на [Part 3, Render Props](https://reactjs.org/docs/render-props.html) и [Part 3, HOC](https://reactjs.org/docs/higher-order-components.html)
Я бы выделил основные вещи:
1. Container components vs presentational components + avoid God-object, stick to SRP	
2. Render props and HOC
3. Scaling React apps (как писать приложение, которое легко масштабируется)

**Comment by uptimizt** [comment]
> почему useReducer + useContext !== Redux

плюсую.

я тоже со старта не оч понял разницу между контекстом и отдельной хранилкой.

было бы круто расписать на примерах в чем разница между контекстом и отдельным хранилищем.

думал что все можно решать через контекст и только с практикой понял что контекст и хранилище это разные инструменты

**Comment by uptimizt** [comment]
большое imho.

но если студент совсем ноль было бы прикольно дать обзор основ:
- сделать простой сайт визитку на SSG с GH Pages. это как основы веба в 90х годах но на современный лад типа GatsbyJS - так делали сайты на заре Интернета
- далее сложнее - что то с SPA & back - типа динамические сайты которые как то взаимодействуют с сервером - продукты про приватные данные - enterprise
- далее что то про SSR - про публичный контент и SEO
- ну и в конце про PWA - что то про завтра и про гибрид веб сайта, мобильного приложения и десктопа

а то многие приходят с нуля, не зная истории, зная только SPA & CRA - начинают его применять везде без разбору - и это плохо для простых статик сайтов или для публичных сайтов про SEO

но это может быть плохо так как 99% приложений на реакте это обычно SPA & CRA и далеко от публичного доступа

**Comment by ragingyngvarr** [comment]
В подготовке программы мы должны учитывать ее длительность - 6 недель. По сути было бы неплохо дать студентам и SSG (и SSR и дать понять разницу на практике). Также было бы очень хорошо дать понять что есть такое PWA и как с помощью реакта можно их писать. Но боюсь что 6 недель для этого банально мало.
Стоит все же делать фокус на базовых моментах Реакта.

Но если говорить про SSR/SSG, может действительно дать возможность попробовать фреймворк как опцию?
Я бы наверное предлагал NextJS:
Gatsby тесно связан с GraphQL. Знать GraphQL - это хорошо, но большинство апишек RESTful (ну или RPC пытающийся казаться рестом). Мы должны готовить студентов к более распространенным сценариям.

**Comment by helenakrasnova** [comment]
1) подписываюсь под идеей с классами -> переписанием на хуки (+ мб разница Component/PureComponent)
2) не знаю сюда ли, но тем не менее, мой консерн по предыдущему курсу - командный таск был интересным и замечательным, но требовал написания довольно большого бэка, из-за чего один студент из трех (среди моей группы) придя на курс по реакту по итогу развивался в ноде. Хотелось бы, чтобы все таки таск был больше завязан на реакт

**Comment by MadaShindeInai** [comment]
Вообще , было бы круто, если бы студенты ознакомились с какими-то основополагающими вещами до начала курса.
Webpack, компонентный подход хотябы.
Тогда:
**1 неделя**: _Можно вычитать лекцию по классам и роутингу._ И таск - Song Bird на классах и JS.
**2 неделя:** _Можно вычитать хуки + редакс._ И таском: Полноценное развёртывание проекта с созданием базовой архитектуры на typescript и sing in-up flow/404/error boundary/private routes.
**3 неделя:** _Можно вычитать GraphQl и SSR + делимся на команды для командной таски._ И таском: Перенос Song Bird на отдельный роут с миграцией его на ts и хуки. Установка в проект Apollo Client. Прохождение https://odyssey.apollographql.com/ .
**4 неделя:** _Прохождение https://odyssey.apollographql.com/  + Лекция про css-in-js технологии и тестированию + делимся на команды для командной таски._
На отдельном роуте пишем аппу с использованием graphql версии API - https://rickandmortyapi.com/. Example: https://work-to-show.netlify.app/dashboard + тесты.
5-6 неделя: командный таск

**Comment by ParfenenkovEdit** [comment]
Соглашусь с @helenakrasnova. У меня также студент полностью сел на бек, хотя не очень этого и хотел. Да, взаимодействие с беком  необходимо понимать, однако это можно сделать на более ранних тасках, а на командный  таск упор строго на Реакт. Может, дать пописать сложные анимации, переходы, графики и дашборды. 
@MadaShindeInai соглашусь по поводу React 18 Features, но не согласен по поводу SSG и SSR. Это нужно, но в 6 недель вряд ли уложимся. Многие работают и давать нагрузку в 40 часов на неделю будет нечестно по отношению ко многим.

**Comment by MadaShindeInai** [comment]
С одной стороны да - работая 40 часов уделать ещё 40 часов на курс сложно, но другой стороны - подстраивать курс под работающих людей тоже такое себе. **В этом наборе большинство студентов будут выпускниками набора по JS, а соответственно вероятность того, что студент трудоустроен - не так уж и велика**. Цель курса - чтобы студенты **получили объём знаний о экосистеме React**, который поможет им **войти в IT**. Т.е. ребята должны быть **конкуретноспособными** трэйни.
Если условный Пётр не работает и может уделять условно 40 часов в неделю - он может сделать таск на 100%. Условный Максим , работает 40 часов и пришёл поучить реакт - вероятно он не сможет выполнять таски на 100%, но тем не менее сможет делать базовый scope.
На основном же курсе никто не делает скидку на то, что кто-то работает. Работает
