### ISSUE TITLE
заменить на пятнашки

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/tasks#514]
```
- [Проект "Museum. DOM & Browser API"](../tasks/museum/museum-dom.md)TODO
```

https://github.com/rolling-scopes-school/tasks/blob/2ddba2baa41f2044d8fedf7d03a26c5afd9e70f0/stage1/README.md#L66

**Comment by irinainina** [comment]
Вёрстка с js лучше вёрстки без js
Замените пожалуйста что-то другое
