### ISSUE TITLE
JS/FE Pre-School 2022, js30

### ISSUE THREAD

**Issue by vpeacock** [rolling-scopes-school/tasks#533]
В названии задания  js30#2.2-image-galery небольшая опечатка - gallery пишется с двумя ll , а у вас одной l .

**Comment by Luffi2539** [comment]
fixed
<img width="470" alt="image" src="https://user-images.githubusercontent.com/43149261/161763145-0634b942-f1f8-40ff-84da-5fe38e12fb0a.png">
