### ISSUE TITLE
UI/UX пожелание: версия PC: Profile -> Edit -> Contacts

### ISSUE THREAD

**Issue by AnnPoltoratskaya** [rolling-scopes-school/tasks#558]
Не используется свободное пространство, а появляется не совсем удобная форма заполнения со скроллом

![image](https://user-images.githubusercontent.com/98906832/158178593-c585d064-a1ef-482f-bf6f-62b5ac4f6968.png)

**Comment by dzmitry-varabei** [comment]
@AnnPoltoratskaya Привет! Все пожеланию по работе RS APP мы собираем тут https://github.com/rolling-scopes/rsschool-app/issue
