### ISSUE TITLE
Same links in the module Stage#1 JavaScript. Evolution

### ISSUE THREAD

**Issue by anna-tanisheva** [rolling-scopes-school/tasks#565]
[Module Stage#1 JavaScript. Evolution](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/js-evolution)

There are two the same links for two different points in the materials.

NPM & package.json:
 [Updating a package](https://docs.npmjs.com/updating-packages-downloaded-from-the-registry)
[Removing a package](https://docs.npmjs.com/updating-packages-downloaded-from-the-registry)

**Comment by Ali-Gator** [comment]
For "Removing a package" I think it should be: https://docs.npmjs.com/uninstalling-packages-and-dependencies

**Comment by dzmitry-varabei** [comment]
@anna-tanisheva @Ali-Gator thanks! fixed!
