### ISSUE TITLE
Исправить Функциональные требования по таску: YouTube client app (Angular. Components. Directives & Pipes task).

### ISSUE THREAD

**Issue by Satlykov** [rolling-scopes-school/tasks#576]
Предлагаю исправить Функциональные требования.
Ссылка на такс: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/angular/components-directives-pipes.md

Сейчас: 

    - The bottom border represents the publication date status. Create a directive to achieve the result
        - If a publication date is less than a month, set border background to green
        - If a publication date is less than 7 days, set border background to blue
        - If a publication date is more than 6 months, set border background to red

Предлагаю: 

    - The bottom border represents the publication date status. Create a directive to change background color of the border.
        - if older than 6 months – Red.
        - if from a month up to 6 months – Yellow
        - if from seven days up to a month – Green.
        - if younger than 7 days – Blue.

**Comment by Pulya10c** [comment]
Thanks, done
