### ISSUE TITLE
Correction of the final task on the React course

### ISSUE THREAD

**Issue by Pulya10c** [rolling-scopes-school/tasks#594]
In the final task https://github.com/rolling-scopes-school/tasks/blob/master/tasks/react/final-task-project-management-app.md on the react course, you need to remove the requirement
![image](https://user-images.githubusercontent.com/30927000/164012458-8c4cec82-730e-4499-95e1-34ccc2b6e89a.png)

because it is not implemented in the backend

**Comment by andron13** [comment]
Исправим

**Comment by dzmitry-varabei** [comment]
@Pulya10c fixed!
