### ISSUE TITLE
Битая ссылка на документацию курса

### ISSUE THREAD

**Issue by MemoS77** [rolling-scopes-school/tasks#601]
На странице: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/react/final-task-project-management-app.md
битая ссылка (в двух местах) на документацию курса
`организация командной работы описана в [Документации курса]`
https://github.com/rolling-scopes-school/tasks/tree/master/stage3/modules/final-task

**Comment by OtabekVaxobov** [comment]
Привет вроде исправлено закройте issue

**Comment by dzmitry-varabei** [comment]
@MemoS77 спасибо! поправили
