### ISSUE TITLE
Пункт за требования к репозиторию.

### ISSUE THREAD

**Issue by AoiHaru1** [rolling-scopes-school/tasks#602]
Здравствуйте, в задание есть пункт о выполнение требований к репозиторию, в котором сказано, что работа должна вестись в приватном репозитории, но тогда каким образом деплоить работу так, чтобы проверяющий убедился в выполнение этого пункта? Ведь помимо этого ему также необходимо проверить коммиты, описание пулл-реквеста. А саму работу даже на гх-пейдж не зальешь, ибо он не работает с приватными репозиториями без pro.  Также если работу сделали перед деплоем публичной, то тогда как проверяющий должен проверить велась ли работа в приватном вообще когда-либо. Так как каким образом необходимо выполнить этот пункт, чтобы получить баллы не нарушив требований к репозиторию.

**Comment by dzmitry-varabei** [comment]
@AoiHaru1 Если необходимо проверить коммиты и описание пулл-реквеста, мы требуем использовать публичный репозиторий.
