### ISSUE TITLE
RSS Virtual Keyboard | Eslint air-bnb rule ('import/extensions')

### ISSUE THREAD

**Issue by Wsko-12** [rolling-scopes-school/tasks#605]
Здравствуйте. Предлагаю внести подпункт в использование конфигурации `eslint-config-airbnb-base` для eslint.
А именно: 
1.  Разрешить добавить в файл `.eslintrc.js` игнорирование правила `'import/extensions'`

Данное правило запрещает использовать расширения файлов в строках `import` в js фалах. Однако, убрав расширение, браузеры выдают ошибку `Failed to load resource: the server responded with a status of 404 (Not Found)`
Что вынуждает (на выбор):
1. Использовать webpack (в ТЗ нет требования по его использованию).
2. Собрать весь скрипт в один файл, без использования модулей и, следовательно, `import` (Однако, в задании поощряется использование ES6 фич, и модули одна из них).
Так же, если объединить весь скрипт в один файл и в нем будет более одного класса, то это вызовет другую ошибку (max-classes-per-file)

**Comment by ThorsAngerVaNeT** [comment]
@Pulya10c

**Comment by Pulya10c** [comment]
Fixed
