### ISSUE TITLE
Stage#1 Week#8 - CSS Mem Slider

### ISSUE THREAD

**Issue by IrLiss** [rolling-scopes-school/tasks#617]
Доброго дня. В критериях оценки есть следующий пункт:
![изображение](https://user-images.githubusercontent.com/50544895/168251193-4a567423-a37d-4b40-b889-eafe16f12531.png)
Если исходить из контекста, то речь идёт о том, что нельзя использовать псевдоэлементы следующего вида:
```css
.class:after{ 
        content: "Text";  /* Добавляем текст при помощи псевдоэлемента*/
        }
```
а не в общем и целом, однако судя по вопросам в дискорде и телеграме у многих возникают вопросы в отношении данной формулировки.

Очень хотелось бы, чтобы вы внесли соответствующие изменения, в данный пункт, если автор задания, хотел чтобы в принципе не использовались псевдоэлементы, то добавьте такое требование не только в критерии оценки, но и в технические требования, как это прописано в отношении препроцессоров, если же речь в действительности идёт только про потоковость, то поясните это в критерии оценки так чтобы Student-у 1 было понятно, что он одолжен смотреть, а не видя слово :after в консоле снимал баллы.

Аналогично, очень хотелось бы конкретики и по поводу позиционирования, речь идёт только о том чтобы не были использованы только конкретные свойства: top, left, right, bottom или же речь идёт о том что нельзя использовать само по себе свойство position (так свойство position: relative; не исключает элемент из потока, чего не скажешь об position: absolute; или position: fixed;). И опять же если есть ограничение на использование свойства position, то почему тогда нет ограничений на использования свойства float? Очень хочется конкретики по данному пункту. Сейчас оно составлено не очень корректно и очень бы не хотелось тратить своё время на выяснения отношений потом с проверяющими или апелляции.

Так же есть вот такой чудесный пункт:
![изображение](https://user-images.githubusercontent.com/50544895/168256211-1c480734-3fdc-4afc-aecb-1e551c99265c.png)
исходя из такой формулировки, проверяющий не должен считать ошибкой если у человека мобильная версия начнётся с 1899 на 999 px. Пропишите требование к мобильной версии корректнее, мобильная версия в понятии автора начинается с 768px или же как в шелтере 320px, чтобы все студенты знали в какой точке проверять мобильность.

Заранее спасибо за внесенные правки, если они конечно же будут!!!

**Comment by helenakrasnova** [comment]
completed
