### ISSUE TITLE
Collect mentor's feedback on React/Angular courses

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#624]
React - https://docs.google.com/forms/d/e/1FAIpQLScQgLS69kggL_ssKk9AYfAT1d0eEUmqxs8CkH06trZRbjNp1Q/viewform
Angular - https://docs.google.com/forms/d/e/1FAIpQLSefo1HxRyiCZs-7-x9HTyUpLtyCgjhU-uVQwDrqGnjSnTh17g/viewform

**Comment by valerydluski** [comment]
@dzmitry-varabei i think it can be closed
