### ISSUE TITLE
Collect student's feedback on React/Angular courses

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#626]
React - https://docs.google.com/forms/d/e/1FAIpQLSd3JEoQjw_BVpdmc3CCfBGr8jP9F2SkeQjnpu4AfTi0ukWaAA/viewform
Angular - https://docs.google.com/forms/d/e/1FAIpQLSed5Plnu8XUFXZdvH2mGMGEap1EmZe6csuRkPAZBgyVuuelVg/viewform

**Comment by valerydluski** [comment]
@dzmitry-varabei i think it can be closed
