### ISSUE TITLE
Test Git & GitHub#2 (What command would let you modify your previous commit?)

### ISSUE THREAD

**Issue by StanislavM31** [rolling-scopes-school/tasks#634]
В тесте на закрепление основ git. Test Git & GitHub#2.
What command would let you modify your previous commit?
![Screenshot_301](https://user-images.githubusercontent.com/60983985/170593956-02366312-dc54-4daa-9dd2-73ffd0c97715.png)
 вроде как --amend.
но ведь полная команда git ammend - поэтому не понятно. --amend или все таки None of these.
Sorry за дотошность

**Comment by Saaabin** [comment]
git --amend "None"

**Comment by dzmitry-varabei** [comment]
@helenakrasnova поправь пожалуйста формулировку вариантов ответа

**Comment by IvanSilent** [comment]
Я наверно не смогу, я начал только обучение с нуля .
--
Отправлено из Mail.ru для Android суббота, 28 мая 2022г., 15:21 +05:00 от Dzmitry Varabei  ***@***.*** :

***@***.*** поправь пожалуйста формулировку вариантов ответа

**Comment by helenakrasnova** [comment]
правильная команда git --amend - верный ответ присутствует в тесте
