### ISSUE TITLE
CV#2 JS/FE Pre-school. Несоответствие задания и критериев оценки.

### ISSUE THREAD

**Issue by lubov-nefed** [rolling-scopes-school/tasks#658]
**Краткое описание проблемы.**

Несоответствие критериев оценки, указанных в задании, и _фактических_ критериев оценки.
В описании задания CV#2. HTML, CSS & Git Basics (https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/html-css-git.md) не указано, что файл index.html будет оцениваться с помощью валидатора. Это вызывает у меня и некоторых других студентов вопросы и непонимание, откуда взялись ошибки и почему оценка ниже ожидаемой, если всё было сделано в соответствии с заданием.

**Подробности.**

В задании написано: "разместите файлы index.html и style.css, предварительно добавив в них любое содержимое. Вёрстка и стилизация CV будет выполняться в следующем задании." Такая формулировка предполагает, что мы делаем просто заготовку для следующего задания, а содержимое файлов не важно и проверяться не будет, но это не так.

В критериях оценки не указано, что будет оцениваться содержимое html-файла. Критерии оценки совпадают с первым заданием, где оценивалась только работа с Git и GitHub: "выполнены требования к репозиторию +50,
выполнены требования к коммитам и Pull Request +50"

**Предложения по решению.**

**Вариант 1.** Убрать валидатор из автотеста (чтобы алгоритм не обращался к валидатору при проверке задания). Вероятно, это повлечет изменения количества начисляемых баллов за правильно выполненные части задания. Возможно, это более сложно реализуемый вариант из двух. Точно не знаю.

**Вариант 2.** Изменить текст задания, чтобы он соответствовал фактическим критериям его оценки.
- В разделе "Порядок работы" изменить пункт 4, удалив текст: "предварительно добавив в них любое содержимое" и добавив текст: "Добавьте в файл index.html базовую структуру html-документа, из этой статьи (https://webref.ru/course/html-basics/valid-document). Ознакомьтесь с понятием валидности и базовой структуры html-документа. Разберите, для чего нужен каждый тег (статья про базовую структуру документа https://ru.hexlet.io/courses/layout-designer-basics/lessons/page-structure/theory_unit)". Такая формулировка мотивирует студентов знакомиться с основами html, начиная уже с этого задания.
Далее в этот же пункт добавить текст: "Проверьте содержимое вашего html документа с помощью валидатора (https://validator.w3.org/#validate_by_input) и исправьте ошибки, если они возникли. Верному результату соответствует надпись 'Document checking completed. No errors or warnings to show'." 
На данный момент после выполнения этих действий появляется ошибка об отсутствии атрибута lang у тега html. Поэтому в этом задании студенту придется столкнуться с ней и исправить ее самостоятельно.
- В разделе "Критерии оценки" добавить пункт:
"выполнены требования к валидности html-верстки".

Сейчас требование ознакомиться с понятием верстка и валидность _существует_ (из-за автоматической проверки файла index.html на валидность). Но это требование является _неявным_. Изменение текста задания сделает это требование _явным_. А также устранит несоответствие заявленных и фактических критериев оценки.

**Comment by kuz0lga** [comment]
я тоже столкнулась с этой проблемой, в задании есть противоречие. не понимаю, зачем в cv2 код проверяется, если задание создать 2 файла.  я начинала проходить нулевой курс раньше, и резюме у меня готово, зимой все в порядке было, 100% выдавало. валидатор не ругался.  что за ужесточение? теперь каждый пробел проверять? зачем?

**Comment by EvgeniTolkach** [comment]
Такая же проблема.
Даже переделал заново CV#1 и CV#2 ибо думал, что ошибка в названии коммитов....
А потом полез в закладки  Issues, где нашел эту тему.

**Comment by Luffi2539** [comment]
@lubov-nefed спасибо за предложение, думаю сделаем второй вариант
