### ISSUE TITLE
Stage#0. Cross-check review bug.

### ISSUE THREAD

**Issue by NickFallman** [rolling-scopes-school/tasks#690]
# Cross-check review bug

В RS App на странице:
[Cross-Check: Review](https://app.rs.school/course/student/cross-check-review?course=js-fe-preschool-2022q2),
в выпадающем списке (меню) задач "Task" ещё не стартовавшие задачи находятся в группе "Active", а уже стартовавшие и активные на данный момент в группе "Expired". Надо наоборот.

![RS-App-bug-2](https://user-images.githubusercontent.com/93594821/174455561-a612728e-fb50-4a55-8218-c7204c72f5bb.png)

**Comment by dzmitry-varabei** [comment]
Duplicate: https://github.com/rolling-scopes/rsschool-app/issues/1371
