### ISSUE TITLE
Тест Clean Code.

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#70]
Предлагаем вопросы/ответы. 
Может быть есть ссылки на хорошие готовые тесты.

Ссылки для вдохновения:
- http://learn.javascript.ru/write-unmain-code 
- https://github.com/airbnb/javascript 
- https://www.oreilly.com/library/view/clean-code/9780136083238/
- https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670

Буду рад любым вашим предложениям!

**Comment by dzmitry-varabei** [comment]
Можно сделать пару вопросов на базе лекции Дениса по рефакторингу - https://github.com/rolling-scopes-school/lectures/blob/master/lectures/refactoring.md

**Comment by davojta** [comment]
js
https://github.com/ryanmcdermott/clean-code-javascript

general common
https://dzone.com/articles/clean-code-summary-and-key-points
https://www.butterfly.com.au/blog/website-development/clean-high-quality-code-a-guide-on-how-to-become-a-better-programmer

general high level
https://www.planetgeek.ch/wp-content/uploads/2013/06/Clean-Code-V2.1.pdf
https://github.com/bhochhi/design-pattern-guide/wiki/clean-code-checklist

**Comment by davojta** [comment]
@dzmitry-varabei а ты хочешь в конце 2 этапе сделать такой тест?

**Comment by dzmitry-varabei** [comment]
@davojta да, ближе к концу stage#2
