### ISSUE TITLE
English test

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#703]
Всем привет! Уникальная возможность протестировать эпамовский сервис оценки уровня английского языка.

Сейчас доступно 4 попытки:
[Попытка #1](https://examinator.epam.com/Assign/3390?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQ3JlYXRlZElkIjo5MTM0LCJ1c2VyQ3JlYXRlZFNTTyI6IjQwNjA3NDE0MDAwMzQ0MjMzNzAiLCJjb250YWluZXJQZXJtaXNzaW9uIjoiQVNTSUdORUQiLCJjb250YWluZXJFeHBpcnlEYXRlIjpudWxsLCJjb250YWluZXJJZCI6IjMzOTAiLCJpYXQiOjE2NTYzMDQ0OTF9.gYcj0jQWMohy1RC7O71JyNYXCkxXIxWhv80DE823THU)
[Попытка #2](https://examinator.epam.com/Assign/3391?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQ3JlYXRlZElkIjo5MTM0LCJ1c2VyQ3JlYXRlZFNTTyI6IjQwNjA3NDE0MDAwMzQ0MjMzNzAiLCJjb250YWluZXJQZXJtaXNzaW9uIjoiQVNTSUdORUQiLCJjb250YWluZXJFeHBpcnlEYXRlIjpudWxsLCJjb250YWluZXJJZCI6IjMzOTEiLCJpYXQiOjE2NTYzMDQ1NTF9.ucpxSah7K9rucm_evFssHIKyKApq9FqQs6Vl9DmiJh8)
[Попытка #3](https://examinator.epam.com/Assign/3392?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQ3JlYXRlZElkIjo5MTM0LCJ1c2VyQ3JlYXRlZFNTTyI6IjQwNjA3NDE0MDAwMzQ0MjMzNzAiLCJjb250YWluZXJQZXJtaXNzaW9uIjoiQVNTSUdORUQiLCJjb250YWluZXJFeHBpcnlEYXRlIjpudWxsLCJjb250YWluZXJJZCI6IjMzOTIiLCJpYXQiOjE2NTYzMDQ1NzJ9._jGLmRHq5_nZaCcrnfiZcD_cVlrJyC-NltQP48xP_bM)
[Попытка #4](https://examinator.epam.com/Assign/3393?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyQ3JlYXRlZElkIjo5MTM0LCJ1c2VyQ3JlYXRlZFNTTyI6IjQwNjA3NDE0MDAwMzQ0MjMzNzAiLCJjb250YWluZXJQZXJtaXNzaW9uIjoiQVNTSUdORUQiLCJjb250YWluZXJFeHBpcnlEYXRlIjpudWxsLCJjb250YWluZXJJZCI6IjMzOTMiLCJpYXQiOjE2NTYzMDQ1OTN9.D3sz6F_Sk9a_ga8Jy-tKyehVMNm6EYUZu24Q5Ld2kWg)

Ваш фидбек можно оставить тут

**Comment by Dranikson** [comment]
Проблемы с мобильной версией. Samsung A8.
1. https://www.awesomescreenshot.com/image/29422409?key=6d52375660db8b7a7f95774db6c9cb8b
2. https://www.awesomescreenshot.com/image/29422453?key=c00f34be8a0b77d91c36dfa9934ab357

В футере всё хорошо до ширины экрана 1100px, потом появляются проблемы:
1. Нет отступа безопасности (contact support) с правой стороны блока.
2. Когда разрешение <  530px улетает футер.
3. Футер информация с копирайт, разезжается вверхи и вниз и судя по всему является причиной выталкивания футера вверх ( но не в бок ).

**Comment by lyutails** [comment]
привет :)
вы конечно там ещё доработаете и перепроверите вопросы, но в глаза бросилось среди прочего думаю помарка - могу быть сильно не права - мне кажется тут третий вариант и должно быть - had not completed the project yet / had completed the project already
![had not completed yet](https://user-images.githubusercontent.com/101958335/176429010-6c016c6f-339f-405d-9d03-6a1695938c0a.JPG)
встретила интересную фразу to strike a happy medium никогда не слышала :)
на принтскрин ругнулся - 'подозреваю вас в читерстве' ^^

**Comment by katpoly** [comment]
> слышала

Это косвенная речь,правильный ответ номер 3

**Comment by alexander-tukach** [comment]
Привет! При выборе варианта ответа на последний вопрос уже нельзя вернуться назад. На мой взгляд это нужно исправить. Иначе потенциальный студент может сделать все что он знает точно, а после захочет вернуться к вопросам над которыми сомневался или вообще пропустил, чтобы не вчитываться и не тратить время (возможность такая есть вплоть до выбора варианта ответа на последний вопрос), а при выборе варианта ответа или вводе буквы в поле последнего вопроса эта возможность пропадает, причем без предупреждения.

**Comment by sandra44dev** [comment]
Привет!
1. За первые два рауда повторился вопрос "Please stop ... such a noise! I can't think"
2. Если выйти из полноэкранного режима, появляется предупреждение, что это будет считаться за жульничество, но не совсем понятно как именно.. Логично установить таймер, типа "Включите полноэкранный режим в течение 1 минуты". Также было бы здорово добавить кнопку, чтобы включался этот режим, а то я растерялась и долго искала fn + f11)
3. При нажатии на enter делается перенос строки, я ожидала переход к следующему вопросу
4. Меня почему-то выбросило к результатам после первых двух раундов (перешла по первой ссылке). (Если это так и задумано, то сори)

**Comment by gentoosiast** [comment]
Спасибо за тест, пока использовал 1 попытку.

- Довольно странно, что вообще нет аудирования.
- Ожидал встретить плотную IT-терминологию, а там максимум про проекты.
- Настраиваешься на 1-1.5 часа работы, но весь тест занял ~15 минут.
- Несколько вопросов повторились.
- Получил только A2, хотя недавно с первого раза сдал 50-минутный EF SET на C2, спокойно читаю на английском без словаря и не только техническую литературу, на очень приличном уровне понимаю на слух.

**Comment by jaysuno0** [comment]
Доброго дня! Спасибо за полезное интересное времяпрепровождение.

Из замеченного:
* Повторение заданий (неоднократное).
* Ну и точность теста довольно плавающая. Понятно, что не супер-ИИ его проводит, да и мозг мог по мере прохождения мог, так сказать, размяться, но... Результаты получились такие - первая попытка сдана на А2, зная что у меня явно не этот левел, пошёл на вторую и получил B2.

**Comment by vdymsh** [comment]
тест просто прервался когда я начал вводить ответ на 4-й вопрос и меня выброссило на эту страницу.

**Comment by Avapolina** [comment]
Привет! 
По попытке 1:
Технические моменты: 
Когда сжимаешь экран, лого ломается: http://dl4.joxi.net/drive/2022/07/01/0037/2262/2451670/70/2c9275e6a1.jpg 
На старте тест выводитсяя в полноэкранный режим, и когда ты возвращаешь все в "стандартный" показ, приходит сообщение о том, что твое действие зафиксировано и, мол, зря ты это сделал, приятель. Но до этого в инструкциях не было ни слово о том, что не стоит выходить из полноэкранного просмотра. И в целом не ясно, как это (а также переход по ссылкам) отражается на баллах. 
Интуитивно не было понятно, что enter работает как новая строчка абзаца, а не как кнопка далее. 

Контентные комменты: 
Не понятно, как расшифровывать результат. b1 - это сколько, много или мало, что мне советуют с таким уровнем делать. 
Кажется, кое-где есть неточности. В одном из вопросов надо было выбратьь глагол к police. И единственный подходящий вариант был - have not arrived. Но ведь правильно has not arrived. 

Комменты по методологии: 
Мне не хватило разных типов вопросов. Было бы классно, если бы они чередовались, и, например, было бы аудиозадание, задание на понимание контекста.

**Comment by Elijah-I** [comment]
> привет :) вы конечно там ещё доработаете и перепроверите вопросы, но в глаза бросилось среди прочего думаю помарка - могу быть сильно не права - мне кажется тут третий вариант и должно быть - had not completed the project yet / had completed the project already ![had not completed yet](https://user-images.githubusercontent.com/101958335/176429010-6c016c6f-339f-405d-9d03-6a1695938c0a.JPG) встретила интересную фразу to strike a happy medium никогда не слышала :) на принтскрин ругнулся - 'подозреваю вас в читерстве' ^^

3й вариант вроде как правильный, потому что yet может трактоваться как "еще", и может как "уже" насколько я мог понять

**Comment by Elijah-I** [comment]
# 1. I'm flying to Paris ... Monday morning
- on
- this
- next
_как догадаться то о каком моменте ижет речь? я вписал `at`, надеюсь угадал... но хотелось бы видеть более однозначные вопросы все же_

# 2. in the big cities the problem of air <choose> can be very serious
- pollution
- polluting
_вроде как подходит и то и то, одно в качестве существительного, другое как наречие_

# 3. you might not like the house ... once, but (не помню что там, что-то насчет того ,что если присмотреться - то он тее понравится)
- at
- visited
- seen
_веротяно имелось в виду `at`, но опять же, `visited` - да, вполне уместно так сказать, `seen` - более разговорный вариант_

**я не гуру в английском, просто выражаю свое впечатление и мысли**

**Comment by katpoly** [comment]
> # 1. I'm flying to Paris ... Monday morning
> 
> - on
> 
> - this
> 
> - next
> 
> _как догадаться то о каком моменте ижет речь? я вписал `at`, надеюсь угадал... но хотелось бы видеть более однозначные вопросы все же_
> 
> 
> 
> # 2. in the big cities the problem of air <choose> can be very serious
> 
> - pollution
> 
> - polluting
> 
> _вроде как подходит и то и то, одно в качестве существительного, другое как наречие_
> 
> 
> 
> # 3. you might not like the house ... once, but (не помню что там, что-то насчет того ,что если присмотреться - то он тее понравится)
> 
> - at
> 
> - visited
> 
> - seen
> 
> _веротяно имелось в виду `at`, но опять же, `visited` - да, вполне уместно так сказать, `seen` - более разговорный вариант_
> 
> 
> 
> **я не гуру в английском, просто выражаю свое впечатление и мысли**

-next
-pollution 
-seen

**Comment by Elijah-I** [comment]
> > # 1. I'm flying to Paris ... Monday morning
> > 
> > * on
> > * this
> > * next
> > 
> > _как догадаться то о каком моменте ижет речь? я вписал `at`, надеюсь угадал... но хотелось бы видеть более однозначные вопросы все же_
> > # 2. in the big cities the problem of air  can be very serious
> > 
> > * pollution
> > * polluting
> > 
> > _вроде как подходит и то и то, одно в качестве существительного, другое как наречие_
> > # 3. you might not like the house ... once, but (не помню что там, что-то насчет того ,что если присмотреться - то он тее понравится)
> > 
> > * at
> > * visited
> > * seen
> > 
> > _веротяно имелось в виду `at`, но опять же, `visited` - да, вполне уместно так сказать, `seen` - более разговорный вариант_
> > **я не гуру в английском, просто выражаю свое впечатление и мысли**
> 
> -next (запланированная поездка,билеты куплены и тд) -pollution (не процесс,а состояние) -seen(типа не посещали,а смотрели дом)

а прикол-то в том, чтоверные варианты:
- on
- (тут не знаю, но 100% оаб подходят номально, потому что часто ing используется как причастие сместо сущ в речи)
- at
