### ISSUE TITLE
Новый список тем для презентаций

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/tasks#73]
Вот старый - https://gist.github.com/DaQuirm/3b6d585f3556039117576854ffd977eb

Предлагаю набросать еще пару десятков тем.
Предложения по темам оставляйте в комментариях.

Спасибо!

**Comment by R1ZEN** [comment]
SVG: Modes, Coordinates, Basic Shapes, Accessibility, Animations;
Compression: gzip, Brotli, Zopfli;
Fonts Loading Strategy;
Server Side Rendering;

**Comment by blohamen** [comment]
Libraries, Frameworks etc.: React Native, React

**Comment by DzmitryDzemyanovich** [comment]
unit testing, elm, ReasonML, Vue, sveltejs

**Comment by PavalEscoba** [comment]
React-Bootstrap,
Reactstrap, 
React + Material UI,

Lodash
Underscore

Gulp
Webpack

Eslint

async/await
Promises
Event Loop
Closures
This
Prototypes/Classes
ES-6

W3C
TC39

**Comment by mikhama** [comment]
Serverless Computing, FaaS, AWS Lambda, Google Cloud Functions, Azure Functions.

**Comment by marusyaganza** [comment]
rxjs, web components, CORS
