### ISSUE TITLE
[React:EN] External resources in Russian

### ISSUE THREAD

**Issue by ragingyngvarr** [rolling-scopes-school/tasks#744]
This is a list of links to extrenals resources (mostly rs.school) which are referenced on the React course.
All those resources are in Russian and needs to be translated to English

1. https://rs.school/react/
2. https://docs.rs.school/#/cross-check-flow
3. https://docs.rs.school/#/teams
4. https://docs.rs.school/#/git-convention?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%B8%D0%BC%D0%B5%D0%BD%D0%B0%D0%BC-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D0%BE%D0%B2
5. https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr

**Comment by ragingyngvarr** [comment]
2. Should be replaced with https://docs.app.rs.school/#/platform/cross-check-flow

**Comment by ragingyngvarr** [comment]
5. Should be replaced with https://docs.app.rs.school/#/platform/pull-request-review-process?id=pull-request-description-must-contain-the-following

**Comment by valerydluski** [comment]
2. https://docs.app.rs.school/#/platform/cross-check-flow

**Comment by valerydluski** [comment]
3. https://docs.app.rs.school/#/platform/team-allocation

**Comment by InikonZS** [comment]
4. Have seen in some english tasks https://www.conventionalcommits.org/en , but maybe is wrong.
