### ISSUE TITLE
Уточнение к заданию Travel 3

### ISSUE THREAD

**Issue by DaryaPit** [rolling-scopes-school/tasks#747]
"Нажатие на кнопку Login (кнопка Account в мобильной версии) показывает сверстанный логин попап + 50
логин попап соответствует верстке его закрытие происходит при клике вне попапа +25"

Предлагаю изменить формулировку этого пункта на:

"Нажатие на кнопку Login (кнопка Account в мобильной версии) показывает сверстанный логин попап + 50
логин попап соответствует верстке  (ПРИ РАЗРЕШЕНИИ 1440px) его закрытие происходит при клике вне попапа +25"

На мобильном разрешении (390px) попап не может соответствовать верстке без появления горизонтальной полосы прокрутки

**Comment by Luffi2539** [comment]
Верстка изначально сделана в 1440px то есть попап должен соответствовать макету
