### ISSUE TITLE
Wrong url

### ISSUE THREAD

**Issue by redvoxdev** [rolling-scopes-school/tasks#752]
https://github.com/rolling-scopes-school/tasks/blob/e119af283534925f1df890cf7bf86e67dfe39f50/tasks/async-race.md?plain=1#L63

**Comment by Chico-rso** [comment]
Do I understand correctly that I need to change the link to the description of the stage2 ?

**Comment by redvoxdev** [comment]
> Do I understand correctly that I need to change the link to the description of the stage2 ?
Don't know for sure
