### ISSUE TITLE
bug: broken link

### ISSUE THREAD

**Issue by dogfrogfog** [rolling-scopes-school/tasks#774]
[link to page with broken link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rsclone/rsclone.md#%D0%94%D0%BB%D1%8F-%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D1%80%D0%B0)

<img width="957" alt="Снимок экрана 2022-08-14 в 15 49 11" src="https://user-images.githubusercontent.com/47758224/184540103-5e883d83-8417-4828-bc0f-5c60599f2dff.png">

**Comment by valerydluski** [comment]
@dzmitry-varabei это rs-clone задание будет переделываться, issue можно закрывать
