### ISSUE TITLE
[2022q3-stage2] [Presentation]: update presentation suggestion

### ISSUE THREAD

**Issue by DenisKhatsuk** [rolling-scopes-school/tasks#775]
Having a link to slides.com as forbidden tool doesn't really benefit anything when [HTML Presentation Framework Reveal](https://github.com/hakimel/reveal.js/) is marked as required. Plus it may mislead students. 

**Proposal**: remove the slides.com mention.

<img width="572" alt="Screenshot 2022-08-15 at 13 14 28" src="https://user-images.githubusercontent.com/60316134/184619375-bcf18bd1-d001-4735-882f-7e8d3dff984a.png">

**Comment by helenakrasnova** [comment]
https://github.com/rolling-scopes-school/tasks/pull/899
