### ISSUE TITLE
Возможные ошибки в тесте CCS Grid

### ISSUE THREAD

**Issue by egor-md** [rolling-scopes-school/tasks#799]
###  CCS Grid

<img width="164" alt="image" src="https://user-images.githubusercontent.com/107609106/191605306-d3583bac-df7a-4733-b54d-62e8cca5f544.png">

Баллы зачисляют за ответ "CSS стандарт"
Согласно спецификации Css Grid Layout - это кандидат на включение в стандарт css. Но на данный момент стандартом css не является. Возможный правильный ответ - "css module"

<img width="756" alt="image" src="https://user-images.githubusercontent.com/107609106/191606583-9c7512b6-1da7-4277-81ab-3800b484bd4a.png">

### inline VS inline-block

<img width="211" alt="image" src="https://user-images.githubusercontent.com/107609106/191606759-0b55be39-701c-4d9b-8c48-f109328d8b5e.png">

Grid-контейнеру со свойством inline-grid можно задать width и height и эти свойства будут работать. Следовательно правильный ответ - "элемент со свойством inline-block", т.к. строчные элементы игнорируют эти свойства css.
Если акцентировать внимание на том, как ведут себя элементы именно СНАРУЖИ, то и inline и inline-block элементы ведут себя снаружи одинаково. Тогда вопрос, что выбирать в качестве правильного ответа?
Баллы за этот вопрос начисляют за ответ "строчный элемент".

### Область vs ячейка

<img width="160" alt="image" src="https://user-images.githubusercontent.com/107609106/191608395-5a42662e-708b-4d5b-b261-b605d40bd8d5.png">

И ячейка(всегда) и область(не всегда) ограничены четырьмя grid-линиями. Если цель вопроса запутать студента словосочетанием "Общее пространство" и студент должен додумать, что "общее" - это сложная структура(и тогда это область), то вопрос хорош. Получается "частное" - это ячейка. 

С другой стороны ячейка всегда ограничена 4-мя грид-линиями, а область можно задать и по другому и тогда она не будет ограничена 4-мя грид-линиями.

### Grid-template

<img width="141" alt="image" src="https://user-images.githubusercontent.com/107609106/191610202-dd1ccf5e-6e9d-44f5-9f0d-0afea891fb1a.png">

Неплохо было бы добавить в варианты ответа еще одно свойство css - grid-template-areas. Оно тоже есть в grid-template.

**Comment by TrickyPie** [comment]
Да, по поводу того чем является грид стандартом или чем-то еще вопрос очень сбивает с толку.

**Comment by Ranpu** [comment]
# Какая запись верна, если нужно создать 3 колонки шириной 100px, 200px, 100px. Высота каждого ряда должна быть 100px.

Правильный ответ не подразумевает что все ряды будут высотой 100px, а только ячейки первого ряда таблицы.

**Comment by Ranpu** [comment]
**Выберите правильное утверждение:**
     - **CSS файл можно переименовать в SCSS и он будет валидным;**
     - **CSS файл можно переименовать в SASS и он будет валидным;**
     - **Все утверждения неверны;**

Может дополнить вопрос информацией о том, валиден ли скармливаемый файл именно для препроцессора? 
В ином случае можно подумать и о том, будет ли переименованный файл валидным при его подключении, например, в html.
