### ISSUE TITLE
Предложения по доработке ТЗ online-zoo. week-1 (stage 1)

### ISSUE THREAD

**Issue by haslie22** [rolling-scopes-school/tasks#800]
Некоторые требования ТЗ не дают в полной мере понимания задания.
+ **Должен быть подсвечен элемент `About`. И он должен перестать быть интерактивным.**
> «Интерактивный» означает, что у кнопки или элемента появляется визуальный эффект или анимация (...) при каких-либо действиях пользователя, например, при наведении курсора.

На макете у пункта меню `About` указано состояние `Active`, если верить фрейму-стайлгайду. То есть между щелчком и отпусканием мыши ссылка должна окрашиваться в оранжевый. Но что имеется в виду под фразой **"он должен перестать быть интерактивным"**? Возможно, имеется в виду, что при клике но нему он не должен окрашиваться в оранжевый цвет, но в какой момент? После первого клика по нему, скролла первого экрана и т.п.?

+ **Все фоновые элементы макета должны растягиваться на всю доступную ширину экрана, если ширина больше 1600px. При этом направляющие должны сохраняться в исходном размере, 1160px.**

Что в данном макете стоит отнести к фоновым элементам макета? Относятся ли к ним черная подложка хэдера, изображение панды? Если к ним относятся также изображения с растениями по краям макета, то они скорее должны "прилипать" к краю экрана и уезжать к краям при уменьшении масштаба, а не растягиваться. Если к ним относится изображение панды, то как при этом оно должно масштабироваться: пропорционально, сдвигая остальные блоки вниз, или должна вырезаться область из центра, чтобы сохранить пропорции блока и расстояние до текста и круглого элемента?

+ **При наведении курсора должна быть анимация выезда текста снизу картинки, где будет информация о названии животного и локации с затемненным задним фоном. Сама картинка, но не карточка, должна увеличиваться на 10px в каждом направлении относительно центра (блок Pets)**

Было бы очень здорово добавить либо прототип для возможности взаимодействия с макетом, либо состояния карточки в стайлгайд, так как данный пункт вызывает много обсуждений и догадок в Дискорде: при выезде текста должна ли затемняться вся картинка либо же лишь область с текстом? Как будет вести себя рамка блока, когда картинка увеличится? Как будет выглядеть пустое место, оставшееся от текста, при ховере? 

+ **Нет кнопки `Watch online`: -5. Кнопка есть, но не интерактивная, или не работает как ссылка на `cam_panda_online`: -2**

Видимо, макет был сокращен, так как страницы `cam_panda_online` нет ни в задании, ни во всем макете, и как в данном случае должна вести себя ссылка не понятно. Аналогичные проблемы встречаются и в других пунктах требований.

+ **Опечатка в слове `watch` на кнопке у блока `watch your favorite animal online`**

У студента возникает вопрос: исправить бросающуюся в глаза опечатку или же оставить для того, чтобы ему не снизили баллы при кросс-чеке из-за несоответствия блока макету?

Доработка этих пунктов существенно сократила бы время студентов на попытки понять, что именно имеется в виду, и сделала бы кросс-чек объективным, так как сейчас данные пункты мешают однозначному толкованию задания.

**P.S.** Было бы очень удобно, если бы в макете также присутствовал вариант для широкого экрана, например, 2560: тогда студентам сразу было бы понятно, каким образом элементы должны тянуться/прилипать к краям. В макете под изображением панды есть фоновая заливка серо-голубым цветом, и из соображений эстетики логично предположить, что в макете должна использоваться такая структура, как, например, на Онлайнере: есть внешний контейнер на 1600, где фон окрашен в белый. Внутри него есть внутренний контейнер для контента на 1160, за его пределы выходят кнопки баннера и растения, которые прилипают к краям внешнего контейнера на 1600. Для всех бОльших разрешений  по бокам появляется фоновая подложка, залитая серо-голубым цветом. Для меня как для дизайнера такой вариант кажется оптимальным: тогда не будет проблем с изображением панды на широких и ультрашироких мониторах, а приклеенные к краям области на 1600 декоративные элементы растений не будут ломать визуальную структуру макета. Но опять же, это субъективное мнение, и хотелось бы избежать различий в толковании задания студентами.

Я готова предложить свою помощь с макетом и доработать его в ближайшее время, добавив вариант для бОльших экранов и прототип для карточек как один из возможных вариантов реализации.

@sergeyshalyapin

**Comment by MOONcitizenX** [comment]
### Должен быть подсвечен элемент About. И он должен перестать быть интерактивным.  
Такое поведение обусловлено текущей страницей. В данном задании нам оставили 2 страницы (двухстраничный макет). Соответсвенно, кнопка ```About``` означает, что мы сейчас находимся на главной странице (```petstory landing```). Такая же ситуация с кнопкой ```Donate```, ее активность означает, что мы находимся на странице ```petstory donate```  
   
### Все фоновые элементы макета должны растягиваться на всю доступную ширину экрана, если ширина больше 1600px. При этом направляющие должны сохраняться в исходном размере, 1160px.  
Меня могут поправить, но я думаю, что к фоновые элементы включают в себя: Giant Panda, фон хэдера и футера, фон блоков (как белый, так и оранжевый градиент), растения, которые должны прилипать к краям экрана на б`ольших размерах экрана.  
  
###  При наведении курсора должна быть анимация выезда текста снизу картинки, где будет информация о названии животного и локации с затемненным задним фоном. Сама картинка, но не карточка, должна увеличиваться на 10px в каждом направлении относительно центра (блок Pets)  
Согласен, что не хватает демки данной фичи, так что все вольны реализовывать на свое усмотрение в соответствии с требованиями :smile:
  
### Нет кнопки Watch online: -5. Кнопка есть, но не интерактивная, или не работает как ссылка на cam_panda_online: -2
Такая же ситуация с ```Map```, попробую сделать ПР, возможно пофиксят. Тут согласен полностью.   
  
### Опечатка в слове watch на кнопке у блока watch your favorite animal online  
Вроде этот вопрос поднимался в дискорде, обещали поправить, но пока не поправили :pensive:

**Comment by sergeyshalyapin** [comment]
> ### Должен быть подсвечен элемент About. И он должен перестать быть интерактивным.
> Такое поведение обусловлено текущей страницей. В данном задании нам оставили 2 страницы (двухстраничный макет). Соответсвенно, кнопка `About` означает, что мы сейчас находимся на главной странице (`petstory landing`). Такая же ситуация с кнопкой `Donate`, ее активность означает, что мы находимся на странице `petstory donate`
> 
> ### Все фоновые элементы макета должны растягиваться на всю доступную ширину экрана, если ширина больше 1600px. При этом направляющие должны сохраняться в исходном размере, 1160px.
> Меня могут поправить, но я думаю, что к фоновые элементы включают в себя: Giant Panda, фон хэдера и футера, фон блоков (как белый, так и оранжевый градиент), растения, которые должны прилипать к краям экрана на б`ольших размерах экрана.
> 
> ### При наведении курсора должна быть анимация выезда текста снизу картинки, где будет информация о названии животного и локации с затемненным задним фоном. Сама картинка, но не карточка, должна увеличиваться на 10px в каждом направлении относительно центра (блок Pets)
> Согласен, что не хватает демки данной фичи, так что все вольны реализовывать на свое усмотрение в соответствии с требованиями 😄
> 
> ### Нет кнопки Watch online: -5. Кнопка есть, но не интерактивная, или не работает как ссылка на cam_panda_online: -2
> Такая же ситуация с `Map`, попробую сделать ПР, возможно пофиксят. Тут согласен полностью.
> 
> ### Опечатка в слове watch на кнопке у блока watch your favorite animal online
> Вроде этот вопрос поднимался в дискорде, обещали поправить, но пока не поправили 😔

Спасибо, это исчерпывающий ответ. Многое уже поправили. Насчет расширения для больших экранов - я бы добавил формат страницы на 1920px, чтобы было понятно, какие элементы тянутся, какие нет.
@haslie22 стукнись мне в личку в дискорде. Я обсужу с тобой работу с макетом. Было бы очень хорошо, если человек, разбирающийся в дизайне сможет пересмотреть работу.
