### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by j-kovalenko** [rolling-scopes-school/tasks#807]
Hello. I am not sure where to post it but the word 'careful' in auto test tasks is misspelled. of course there should be only one 'l'. Thank you.
![image](https://user-images.githubusercontent.com/85246748/192254222-f96c450d-9ca9-49d8-a88b-8a34ac7244b5.png)

**Comment by dzmitry-varabei** [comment]
@j-kovalenko thanks! fixed
