### ISSUE TITLE
Попап при нажатии на отзыв в блоке Testimonials

### ISSUE THREAD

**Issue by AliQuickC** [rolling-scopes-school/tasks#820]
Task Online-zoo
Неделя 3

Попап при нажатии на отзыв в блоке Testimonials.
Открываем на ширине экрана 640px или более так, чтобы были видны 3 укороченных отзыва.

я так понимаю, должно быть "640px или менее", т.к. укороченные отзывы на меньшей ширине отображаются

**Comment by sergeyshalyapin** [comment]
Привет, нет, все верно. Точка перехода у кого-то может быть 640px, у кого-то может быть 768px, и так до 999px. Имелось ввиду с момента, как они трансформируются в вертикальную сетку.
