### ISSUE TITLE
Возможные ошибки в тесте DOM Api

### ISSUE THREAD

**Issue by Ranpu** [rolling-scopes-school/tasks#821]
#### Вопрос: ``` Выберите утверждения, справедливые для <input> с атрибутом type, равным date ```
Судя по информации из начала статьи на MDN, date может поддерживаться не всеми браузерами.
![изображение](https://user-images.githubusercontent.com/12532359/194321708-4a3e43cd-08c1-454f-b0d8-6e7dcc1cb010.png)
При этом, в разделе [Browser compatibility](https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/date#browser_compatibility), на который ссылается эта часть статьи, указано что данный тэг с данным атрибутом имеет **Full support**
![изображение](https://user-images.githubusercontent.com/12532359/194320710-9d115423-344c-42a7-8721-354a7fc86110.png)

Из-за чего не понятно почему в тесте справедливым утверждением является ```не все браузеры поддерживают date```

**Comment by helenakrasnova** [comment]
![image](https://user-images.githubusercontent.com/44213581/195098480-4bc9ad2c-c427-4863-89b7-b8ef0f8b882c.png)
источник: www.w3schools.com/

**Comment by Ranpu** [comment]
А есть заявление об отмене поддержки Microsoft IE начиная с 15 июня 2022 года: https://www.microsoft.com/en-us/download/internet-explorer.aspx

Я понимаю что легаси наше все, НО может тогда изменить утверждение в этом варианте на 'В неподдерживаемых браузерах элемент будет отображаться как обычный ```<input type="text">```'?

**Comment by helenakrasnova** [comment]
вопрос в тесте направлен на обучение в том числе в поиске информации и выделения нужного, чтение официальной документации 
в данный момент ответ является верным, ссылку на документацию я приложила
