### ISSUE TITLE
CodeWars problems

### ISSUE THREAD

**Issue by dmitrygurinovich** [rolling-scopes-school/tasks#822]
### Tasks are retired and cant't be submited:
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/preschool-2022-codewars1.md
- 8 kyu https://www.codewars.com/kata/can-we-divide-it

https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/preschool-2022-codewars2.md
- 7 kyu https://www.codewars.com/kata/sum-with-arrows/

**Because of them, it is impossible to get the maximum score**

**Comment by dzmitry-varabei** [comment]
@natein посмотри пожалуйста

**Comment by natein** [comment]
> @natein посмотри пожалуйста

Это срочно?
Я собиралась проверить все задачи поближе к началу курса. Сейчас на codewars очень активно удаляют дубликаты и за 2 месяца до начала курса могут удалить ещё некоторые задачи.

**Comment by dzmitry-varabei** [comment]
@natein это подождет

**Comment by natein** [comment]
Задача https://www.codewars.com/kata/can-we-divide-it заменена на https://www.codewars.com/kata/quarter-of-the-year

Задача https://www.codewars.com/kata/sum-with-arrows/ заменена на https://www.codewars.com/kata/minimize-sum-of-array-array-series-number-1
