### ISSUE TITLE
Minor changes to figma layout

### ISSUE THREAD

**Issue by lyutails** [rolling-scopes-school/tasks#863]
Hey :) 
would suggest to add logo and navigation to 'header' for 1440 (as it's already done for 768 and 380) - atm header includes the whole welcome section
and maybe add leaves to the right side of welcome section for 768 (already so on this pic)
![image](https://user-images.githubusercontent.com/101958335/204146208-f61d8340-a197-469c-a136-5102a084332c.png)
... though maybe it's supposed to be so :)
... also logo (leaf and Plants) are not vertically aligned with navbar on 1440
... also in 'service' section there is 'gargens' instead of 'gardens'
![image](https://user-images.githubusercontent.com/101958335/204151842-efb28e13-20ce-460a-a250-e6fe8cbfbb0c.png)

**Comment by anmaiden** [comment]
Hello! Thanks for your issue. The layout has been corrected according to some comments.
1) the logo has been centered relative to the nav
2) The typo on the buttons has been fixed.
3) changed the appearance of the 768 section "welcome"
4) in 1440 header and section Welcome section was also divided

**Comment by Luffi2539** [comment]
@anmaiden Thank you for attendance!
