### ISSUE TITLE
Small issue in Plants#1 task, checklist bug? & invalid link

### ISSUE THREAD

**Issue by vbloodi** [rolling-scopes-school/tasks#904]
- Issues list:
1. This checklist link does not contain a checklist form for the Plants layout (there is only Travel)
Link: [https://github.com/...](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-plants1)

2. When trying to open any link in the checklist in a new window, .json files are opened (probably not a bug)
Link: [https://rolling-scopes-school...](https://rolling-scopes-school.github.io/checklist/)

3. The link in the materials to [Старт в Figma для верстальщика] (https://htmlacademy.ru/blog/useful/figma) is outdated and leads to a non-existent page (error 404)
Link: [https://github.com/...](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md)

**Comment by Luffi2539** [comment]
1. Checklist added.
2. Not a bug
3. removed from links

@vbloodi thanks for notification
