### ISSUE TITLE
Ветка gh-pages в приватном репозитории создаётся "отдельно" от main

### ISSUE THREAD

**Issue by turn2river** [rolling-scopes-school/tasks#908]
Сейчас ветка gh-pages создаётся автоматически в приватном репозитории, при этом она создаётся отдельно от main и в неё нельзя открыть Pull Request из ветки разработки. Чтобы это починить, надо удалить ветку gh-pages на Github, потом идти в dashboard и нажимать кнопку Fix Repo.

Предлагаю:
- не создавать автоматически ветку gh-pages в приватном репозитории
- поменять кнопку "Fix Repo" на "Create gh-pages branch" (это именно то, что делает кнопка)

**Comment by valerydluski** [comment]
@ThorsAngerVaNeT I'm sorry, we fixed this issue
