### ISSUE TITLE
JS/FE 2022Q3 Stage#2. Possible mistake in Design Patterns Test

### ISSUE THREAD

**Issue by aleksryab** [rolling-scopes-school/tasks#935]
Hi! My answer is marked as incorrect. But I think the answer is correct:
![design-pattern-test-mistake](https://user-images.githubusercontent.com/57621627/215683285-802f6bd9-4509-4f7e-be31-93773a5a1640.jpg)
By the way, thanks for new feature of checking incorrect answers

**Comment by helenakrasnova** [comment]
Please, provide an information and links to documentation, why do you think that your answer was correct

**Comment by aleksryab** [comment]
Sure, my source: https://refactoring.guru/ru/design-patterns/observer
> Наблюдатель — это поведенческий паттерн проектирования, который создаёт механизм подписки, позволяющий одним объектам следить и реагировать на события, происходящие в других объектах.

That's exactly what I answered)

**Comment by helenakrasnova** [comment]
fixed
