### ISSUE TITLE
shelter. week-1 - Фиксированная вёрстка

### ISSUE THREAD

**Issue by Den0702** [rolling-scopes-school/tasks#994]
Неточность в описании задания [shelter. week-1 - Фиксированная вёрстка](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md#shelter-week-1---%D1%84%D0%B8%D0%BA%D1%81%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%B0%D1%8F-%D0%B2%D1%91%D1%80%D1%81%D1%82%D0%BA%D0%B0) 

"Ширина контента 1280рх не должна изменяться при _изменении_ размера окна браузера."

Всвязи с чем возникало много вопросов, в тч. должна ли появляться горизонтальная прокрутка.

Предлагаю поменять на "Ширина контента 1280рх не должна изменяться при увеличении ширины окна браузера более чем на 1280рх."

**Comment by WiiJoy** [comment]
Привет!

Фиксированная верстка (буквально) изначально предполагает, что работа будет иметь фиксированный размер при любой ширине страницы. Это тема и итог выполнения первой части таска Shelter. При этом проверка на уменьшение ширины меньше 1280px не ведется: она ограничена поведением на увеличение ширины или уменьшения масштаба страницы:

<img width="941" alt="Снимок экрана 2023-03-30 в 09 02 34" src="https://user-images.githubusercontent.com/73646765/228717736-3ae6c78a-118c-4f7a-9704-309f24fd5837.png">
